import { describe, expect, it } from 'vitest';
import { createHarness, MemoryStorage, seedActiveClient, seedEngagement, seedStaff, emptyClient } from './harness';
import { STORAGE_KEYS } from '../repositories/localStorage/keys';
import { BACKUP_DATA_KEYS } from '../utils/backupValidation';
import { createMetadata } from '../services/helpers';
import type { AuditReportVersion, Client, EngagementFileLock, InvoiceRecord } from '../types/models';
import { toCsv } from '../utils/download';
import { todayIso } from '../utils/dates';

const today=todayIso();
const tomorrow=(()=>{const d=new Date(`${today}T00:00:00`);d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)})();
class FailOnceStorage extends MemoryStorage{failKey='';armed=false;override setItem(key:string,value:string){if(this.armed&&key===this.failKey){this.armed=false;throw new Error('Injected write failure');}super.setItem(key,value)}}

function directInvoice(clientId:string,engagementId:string,number='INV-0001',outstanding=1000):InvoiceRecord{
  return {...createMetadata('Issued','Tester'),invoiceNumber:number,clientId,engagementId,invoiceDate:today,dueDate:tomorrow,serviceType:'Audit',billingPeriod:'2026',currency:'BDT',grossAmount:outstanding,discount:0,taxVatAmount:0,netAmount:outstanding,amountCollected:0,outstandingAmount:outstanding,billingBasis:'Fixed Fee',billingStatus:'Billed',preparedById:'',reviewerId:'',approvalDate:today,issueDate:today,fileReference:'',adjustmentReason:'',notes:''};
}
function directReport(engagementId:string,version:number,current=true,final=false):AuditReportVersion{
  return {...createMetadata(final?'Final Approved':'Draft','Tester'),engagementId,reportType:'Independent Auditor Report',versionNumber:version,versionDate:today,financialStatementVersionReference:`FS-${version}`,proposedOpinion:'Unmodified',basisSummary:'',emphasisOfMatter:'',otherMatter:'',goingConcernSection:'',otherInformationSection:'',responsibilitiesSummary:'',auditorResponsibilitiesSummary:'',managerReviewerId:'',partnerApproverId:'',managerReviewDate:'',partnerApprovalDate:'',currentVersion:current,finalVersion:final,fileReference:'',returnReason:'',notes:''};
}

describe('Complete Phase 6 integration hardening',()=>{
  it('341 searches clients and routes to the client profile',async()=>{const h=createHarness();const client=await seedActiveClient(h,{clientCode:'CL-SEARCH',legalName:'Global Search Limited'});const results=await h.services.phase6.search('Global Search');expect(results[0]).toMatchObject({type:'Client',id:client.id,route:`/clients/${client.id}`});});
  it('342 searches engagements and routes to the engagement workspace',async()=>{const h=createHarness();const engagement=await seedEngagement(h,{engagementCode:'ENG-SEARCH'});const result=(await h.services.phase6.search('ENG-SEARCH')).find(r=>r.type==='Engagement');expect(result?.route).toBe(`/engagements/${engagement.id}`);});
  it('343 search returns a clean empty result for unmatched text',async()=>{const h=createHarness();expect(await h.services.phase6.search('definitely-no-match')).toEqual([]);});
  it('344 service-specific assignment search excludes a mismatched engagement service',async()=>{const h=createHarness();const engagement=await seedEngagement(h);await h.repositories.taxAssignments.create({...createMetadata('Draft','Tester'),engagementId:engagement.id,assessmentYear:'2026',taxAssignmentType:'Income Tax Return',taxpayerTin:'TIN',filingDeadline:tomorrow,documentsRequired:'',computationVersion:'',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',submissionDate:'',submissionReference:'',assessmentHearingDate:'',responsibleStaffId:'',managerReviewerId:'',managerReviewDate:'',status:'Draft',notes:''});expect((await h.services.phase6.search('TAX')).some(r=>r.type==='Tax Assignment')).toBe(false);});
  it('345 reference numbering skips existing values without duplicates',()=>{const h=createHarness();expect(h.services.phase6.nextReference('invoice',['INV-0001','inv-0002'])).toBe('INV-0003');});
  it('346 reference numbering respects configured prefixes',()=>{const h=createHarness();const settings=h.services.settings.get();h.services.settings.save({...settings,numbering:{...settings.numbering,referencePrefixes:{...settings.numbering.referencePrefixes,invoice:'BILL-'}}});expect(h.services.phase6.nextReference('invoice',[])).toBe('BILL-0001');});
  it('347 numbering health detects duplicate references created outside services',async()=>{const h=createHarness();const first=await seedActiveClient(h);await h.repositories.clients.create({...first,id:crypto.randomUUID(),legalName:'Duplicate code record',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const health=await h.services.phase6.numberingHealth();expect(health.duplicates.some(i=>i.module==='Clients'&&i.code==='DUPLICATE_REFERENCE')).toBe(true);});
  it('348 integration scan detects corrupt module JSON without crashing',async()=>{const storage=new MemoryStorage();const h=createHarness(storage);storage.setItem(STORAGE_KEYS.tasks,'{broken');const health=await h.services.phase6.scanIntegration();expect(health.corruptModules).toBe(1);expect(health.issues.some(i=>i.code==='CORRUPT_MODULE')).toBe(true);});
  it('349 corrupt module reset keeps a local recovery snapshot',()=>{const storage=new MemoryStorage();const h=createHarness(storage);storage.setItem(STORAGE_KEYS.tasks,'{broken');const key=h.services.phase6.resetCorruptModule(STORAGE_KEYS.tasks);expect(storage.getItem(STORAGE_KEYS.tasks)).toBeNull();expect(storage.getItem(key)).toContain('{broken');});
  it('350 raw recovery snapshot covers every application storage key',()=>{const h=createHarness();const snapshot=h.services.phase6.createRawRecoverySnapshot();expect(Object.keys(snapshot.data)).toContain(STORAGE_KEYS.clients);expect(Object.keys(snapshot.data)).toContain(STORAGE_KEYS.followUps);expect(Object.keys(snapshot.data)).toContain(STORAGE_KEYS.settings);});
  it('351 integration scan detects invoice/collection balance mismatch',async()=>{const h=createHarness();const engagement=await seedEngagement(h);const invoice=directInvoice(engagement.clientId,engagement.id);await h.repositories.invoices.create({...invoice,amountCollected:250,outstandingAmount:750});const health=await h.services.phase6.scanIntegration();expect(health.issues.some(i=>i.code==='INVOICE_BALANCE_MISMATCH')).toBe(true);});
  it('352 integration scan detects multiple current report versions',async()=>{const h=createHarness();const engagement=await seedEngagement(h);await h.repositories.reportVersions.create(directReport(engagement.id,1,true));await h.repositories.reportVersions.create(directReport(engagement.id,2,true));const health=await h.services.phase6.scanIntegration();expect(health.issues.some(i=>i.code==='MULTIPLE_CURRENT_RECORDS'&&i.module==='Report Versions')).toBe(true);});
  it('353 integration scan detects a lock status mismatch',async()=>{const h=createHarness();const engagement=await seedEngagement(h);const lock:EngagementFileLock={...createMetadata('Locked','Tester'),engagementId:engagement.id,lockDate:new Date().toISOString(),lockedById:'',lockReason:'Final lock',finalRecordCounts:{},notes:''};await h.repositories.engagementLocks.create(lock);const health=await h.services.phase6.scanIntegration();expect(health.issues.some(i=>i.code==='LOCK_STATUS_MISMATCH')).toBe(true);});
  it('354 dashboard overdue deadline count matches source records',async()=>{const h=createHarness();const engagement=await seedEngagement(h);const staff=await seedStaff(h,'Assistant','A-P6');await h.services.deadlines.save({clientId:engagement.clientId,engagementId:engagement.id,deadlineType:'Statutory',description:'Past deadline',dueDate:'2020-01-01',ownerId:staff.id,priority:'High',status:'Open',completionDate:'',changeReason:'',notes:''},'Tester');const summary=await h.services.dashboard.getSummary({period:'',partnerId:'',managerId:'',service:'',clientType:'',engagementStatus:''},14);expect(summary.overdueDeadlines).toBe(1);});
  it('355 dashboard total outstanding equals eligible invoice balances',async()=>{const h=createHarness();const engagement=await seedEngagement(h);await h.repositories.invoices.create(directInvoice(engagement.clientId,engagement.id,'INV-A',1200));await h.repositories.invoices.create({...directInvoice(engagement.clientId,engagement.id,'INV-B',500),status:'Cancelled'});const summary=await h.services.dashboard.getSummary({period:'',partnerId:'',managerId:'',service:'',clientType:'',engagementStatus:''},14);expect(summary.totalOutstandingFees).toBe(1200);});
  it('356 partner report outstanding is restricted to that partner portfolio',async()=>{const h=createHarness();const e1=await seedEngagement(h);const p2=await seedStaff(h,'Partner','P-999');const m2=await seedStaff(h,'Manager','M-999');const c2=await h.services.clients.create({...emptyClient,clientCode:'CL-999',legalName:'Second Client',status:'Active'},'Tester');const e2=await h.services.engagements.create({...e1,id:undefined as never,engagementCode:'ENG-999',clientId:c2.id,responsiblePartnerId:p2.id,responsibleManagerId:m2.id},'Tester');await h.repositories.invoices.create(directInvoice(e1.clientId,e1.id,'INV-1',100));await h.repositories.invoices.create(directInvoice(e2.clientId,e2.id,'INV-2',900));const report=await h.services.phase5.partnerReports(e1.responsiblePartnerId);expect(Object.values(report.outstandingFees).reduce((a,b)=>a+b,0)).toBe(100);});
  it('357 client outstanding excludes cancelled and written-off invoices',async()=>{const h=createHarness();const e=await seedEngagement(h);await h.repositories.invoices.create(directInvoice(e.clientId,e.id,'INV-1',100));await h.repositories.invoices.create({...directInvoice(e.clientId,e.id,'INV-2',500),status:'Written Off'});const report=await h.services.phase5.clientReport(e.clientId);expect(report.outstanding).toBe(100);});
  it('358 custom-period workload capacity scales from weekly capacity',async()=>{const h=createHarness();const staff=await seedStaff(h,'Assistant','A-CAP');const row=(await h.services.phase5.getWorkload('2026-01-01:2026-01-14')).find(r=>r.staffId===staff.id);expect(row?.capacityHours).toBe(80);});
  it('359 full backup uses schema 7.0 and includes every implemented module',async()=>{const h=createHarness();await seedActiveClient(h);const backup=h.services.backup.createBackup();expect(backup.schemaVersion).toBe('7.0');expect(Object.keys(backup.data).sort()).toEqual([...BACKUP_DATA_KEYS].sort());});
  it('360 backup preview rejects tampered module counts',async()=>{const h=createHarness();await seedActiveClient(h);const backup=h.services.backup.createBackup();backup.moduleCounts[STORAGE_KEYS.clients]=99;const preview=h.services.backup.preview(backup);expect(preview.valid).toBe(false);expect(preview.errors.join(' ')).toContain('moduleCounts');});
  it('361 backup preview rejects tampered integrity summary',async()=>{const h=createHarness();await seedActiveClient(h);const backup=h.services.backup.createBackup();backup.integritySummary='incorrect';const preview=h.services.backup.preview(backup);expect(preview.valid).toBe(false);expect(preview.errors.join(' ')).toContain('integrity summary');});
  it('362 Phase 5 schema 6.0 backup is rejected with a precise migration message',async()=>{const h=createHarness();await seedActiveClient(h);const backup=h.services.backup.createBackup();backup.schemaVersion='6.0';backup.settings.schemaVersion='6.0';backup.meta.schemaVersion='6.0';const preview=h.services.backup.preview(backup);expect(preview.valid).toBe(false);expect(preview.errors.join(' ')).toContain('Phase 5 backup schema 6.0');});
  it('363 restore rollback remains atomic for a Phase 6 backup',async()=>{const source=createHarness();await seedActiveClient(source);const backup=source.services.backup.createBackup();const storage=new FailOnceStorage();const target=createHarness(storage);const before=storage.getItem(STORAGE_KEYS.settings);storage.failKey=STORAGE_KEYS.clients;storage.armed=true;const result=await target.services.backup.restore(backup,'replace','Tester');expect(result.rolledBack).toBe(true);expect(result.rollbackSuccessful).toBe(true);expect(storage.getItem(STORAGE_KEYS.settings)).toBe(before);});
  it('364 CSV export neutralises formulas and preserves Bangla Unicode',()=>{const csv=toCsv([{name:'বাংলা নাম',value:'=2+2',note:'a,"b"'}]);expect(csv).toContain('বাংলা নাম');expect(csv).toContain("'=2+2");expect(csv).toContain('a,""b""');});
  it('365 invalid reference prefixes are rejected by settings validation',()=>{const h=createHarness();const settings=h.services.settings.get();expect(()=>h.services.settings.save({...settings,numbering:{...settings.numbering,referencePrefixes:{...settings.numbering.referencePrefixes,invoice:''}}})).toThrow(/Settings could not be saved/);});
  it('366 reference scope validator rejects blank and excessively long values',()=>{const h=createHarness();expect(()=>h.services.phase6.validateReferenceScope('')).toThrow();expect(()=>h.services.phase6.validateReferenceScope('X'.repeat(81))).toThrow();});
});
