import { describe, expect, it } from 'vitest';
import { createHarness, MemoryStorage, seedActiveClient, seedEngagement, seedStaff } from './harness';
import { STORAGE_KEYS } from '../repositories/localStorage/keys';
import { todayIso } from '../utils/dates';

const today=todayIso();
const yesterday=(()=>{const d=new Date(`${today}T00:00:00`);d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)})();
const tomorrow=(()=>{const d=new Date(`${today}T00:00:00`);d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)})();
const old='2020-01-01';
class FailOnceStorage extends MemoryStorage{failKey='';armed=false;override setItem(key:string,value:string){if(this.armed&&key===this.failKey){this.armed=false;throw new Error('Injected write failure');}super.setItem(key,value)}}
async function ctx(){const h=createHarness();const engagement=await seedEngagement(h);const assistant=await seedStaff(h,'Assistant','A-001');const reviewer=await seedStaff(h,'Manager','M-002');const client=await h.repositories.clients.getById(engagement.clientId);return{h,engagement,assistant,reviewer,client:client!}}
const timesheet=(staffId:string,engagementId:string)=>({staffId,engagementId,activityCode:'AUD',activityType:'Client Work',workDate:yesterday,hours:8,description:'Audit work',billable:true,reviewerId:'',reviewDate:'',status:'Draft' as const,returnReason:'',notes:''});
const expense=(staffId:string,engagementId:string)=>({engagementId,expenseDate:yesterday,expenseCategory:'Travel',amount:100,currency:'BDT',description:'Travel',receiptReference:'',claimedById:staffId,reviewerId:'',approvalDate:'',reimbursementDate:'',status:'Draft' as const,rejectionReason:'',notes:''});
const invoice=(clientId:string,engagementId:string,preparedById:string)=>({invoiceNumber:'INV-001',clientId,engagementId,invoiceDate:yesterday,dueDate:tomorrow,serviceType:'Audit',billingPeriod:'2026',currency:'BDT',grossAmount:1000,discount:100,taxVatAmount:150,netAmount:0,amountCollected:0,outstandingAmount:0,billingBasis:'Fixed Fee',billingStatus:'Billed',preparedById,reviewerId:'',approvalDate:'',issueDate:'',fileReference:'',adjustmentReason:'',status:'Draft' as const,notes:''});
const collection=(invoiceId:string,clientId:string,engagementId:string,recordedById:string)=>({collectionReference:'COL-001',invoiceId,clientId,engagementId,collectionDate:yesterday,amount:400,method:'Bank',bankCashReference:'BANK-1',recordedById,status:'Draft' as const,reversalReason:'',notes:''});
const communication=(clientId:string,engagementId:string,ownerId:string)=>({clientId,engagementId,communicationDateTime:`${yesterday}T10:00`,communicationType:'Email' as const,contactPerson:'Finance Manager',subject:'Documents',summary:'Requested records',commitments:'Provide records',followUpRequired:true,followUpOwnerId:ownerId,followUpDate:tomorrow,confidentialityLevel:'Internal',fileReference:'',status:'Draft' as const,amendmentReason:'',notes:''});
const followup=(clientId:string,engagementId:string,ownerId:string)=>({followUpReference:'FU-001',sourceType:'Manual',sourceId:'',clientId,engagementId,ownerId,dueDate:tomorrow,priority:'Normal' as const,actionRequired:'Call client',completionComment:'',completedDate:'',status:'Open' as const,cancellationReason:'',notes:''});

describe('Complete Phase 5 services',()=>{
 it('295 creates a valid timesheet',async()=>{const c=await ctx();const r=await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');expect(r.hours).toBe(8)});
 it('296 blocks future timesheet dates',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveTimesheet({...timesheet(c.assistant.id,c.engagement.id),workDate:tomorrow},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('297 enforces daily 24-hour limit',async()=>{const c=await ctx();await c.h.services.phase5.saveTimesheet({...timesheet(c.assistant.id,c.engagement.id),hours:16},'Tester');await expect(c.h.services.phase5.saveTimesheet({...timesheet(c.assistant.id,c.engagement.id),activityCode:'TWO',hours:9},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('298 client work requires engagement',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveTimesheet({...timesheet(c.assistant.id,''),engagementId:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('299 reviewer cannot equal timesheet preparer',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveTimesheet({...timesheet(c.assistant.id,c.engagement.id),status:'Approved',reviewerId:c.assistant.id,reviewDate:today},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('300 returned timesheet requires reason',async()=>{const c=await ctx();const r=await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');const s=await c.h.services.phase5.saveTimesheet({...r,status:'Submitted'},'Tester',r.id);await expect(c.h.services.phase5.saveTimesheet({...s,status:'Returned'},'Tester',r.id)).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('301 approved timesheet becomes read-only',async()=>{const c=await ctx();let r=await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');r=await c.h.services.phase5.saveTimesheet({...r,status:'Submitted'},'Tester',r.id);r=await c.h.services.phase5.saveTimesheet({...r,status:'Approved',reviewerId:c.reviewer.id,reviewDate:today},'Tester',r.id);await expect(c.h.services.phase5.saveTimesheet({...r,description:'Changed'},'Tester',r.id)).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('302 detects workload over-allocation',async()=>{const c=await ctx();const s=await c.h.repositories.staff.getById(c.assistant.id);await c.h.repositories.staff.update({...s!,weeklyCapacityHours:4});await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');const row=(await c.h.services.phase5.getWorkload(`${yesterday}:${today}`)).find(x=>x.staffId===c.assistant.id);expect(row?.overAllocation).toBe(true)});
 it('303 workload uses actual timesheet hours',async()=>{const c=await ctx();await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');expect((await c.h.services.phase5.getWorkload(`${yesterday}:${today}`)).find(x=>x.staffId===c.assistant.id)?.timesheetActualHours).toBe(8)});
 it('304 creates valid expense',async()=>{const c=await ctx();expect((await c.h.services.phase5.saveExpense(expense(c.assistant.id,c.engagement.id),'Tester')).amount).toBe(100)});
 it('305 expense receipt threshold is enforced',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveExpense({...expense(c.assistant.id,c.engagement.id),amount:6000},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('306 expense approval requires independent reviewer',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveExpense({...expense(c.assistant.id,c.engagement.id),status:'Approved',reviewerId:c.assistant.id,approvalDate:today},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('307 rejected expense requires reason',async()=>{const c=await ctx();let r=await c.h.services.phase5.saveExpense(expense(c.assistant.id,c.engagement.id),'Tester');r=await c.h.services.phase5.saveExpense({...r,status:'Submitted'},'Tester',r.id);await expect(c.h.services.phase5.saveExpense({...r,status:'Rejected'},'Tester',r.id)).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('308 invoice net amount is calculated',async()=>{const c=await ctx();const r=await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');expect(r.netAmount).toBe(1050);expect(r.outstandingAmount).toBe(1050)});
 it('309 invoice number is unique',async()=>{const c=await ctx();await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');await expect(c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('310 invoice due date chronology is enforced',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveInvoice({...invoice(c.client.id,c.engagement.id,c.assistant.id),dueDate:old},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('311 issued invoice requires approval and issue date',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveInvoice({...invoice(c.client.id,c.engagement.id,c.assistant.id),status:'Issued'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('312 confirmed collection updates outstanding',async()=>{const c=await ctx();let i=await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');i=await c.h.services.phase5.saveInvoice({...i,status:'Review Pending'},'Tester',i.id);i=await c.h.services.phase5.saveInvoice({...i,status:'Approved',reviewerId:c.reviewer.id,approvalDate:yesterday},'Tester',i.id);i=await c.h.services.phase5.saveInvoice({...i,status:'Issued',issueDate:yesterday},'Tester',i.id);let r=await c.h.services.phase5.saveCollection(collection(i.id,c.client.id,c.engagement.id,c.assistant.id),'Tester');await c.h.services.phase5.saveCollection({...r,status:'Confirmed'},'Tester',r.id);const saved=await c.h.repositories.invoices.getById(i.id);expect(saved?.outstandingAmount).toBe(650);expect(saved?.status).toBe('Partially Collected')});
 it('313 collection cannot exceed outstanding',async()=>{const c=await ctx();const i=await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');await expect(c.h.services.phase5.saveCollection({...collection(i.id,c.client.id,c.engagement.id,c.assistant.id),amount:2000,status:'Confirmed'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('314 duplicate collection reference is blocked',async()=>{const c=await ctx();const i=await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');await c.h.services.phase5.saveCollection(collection(i.id,c.client.id,c.engagement.id,c.assistant.id),'Tester');await expect(c.h.services.phase5.saveCollection(collection(i.id,c.client.id,c.engagement.id,c.assistant.id),'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('315 reversal requires reason',async()=>{const c=await ctx();const i=await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');let r=await c.h.services.phase5.saveCollection({...collection(i.id,c.client.id,c.engagement.id,c.assistant.id),status:'Confirmed'},'Tester');await expect(c.h.services.phase5.saveCollection({...r,status:'Reversed'},'Tester',r.id)).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('316 final communication requires subject and summary',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveCommunication({...communication(c.client.id,c.engagement.id,c.assistant.id),subject:'',status:'Final'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('317 communication follow-up creates follow-up record',async()=>{const c=await ctx();await c.h.services.phase5.saveCommunication({...communication(c.client.id,c.engagement.id,c.assistant.id),status:'Final'},'Tester');expect((await c.h.services.phase5.listFollowUps()).length).toBe(1)});
 it('318 final communication correction requires amended status and reason',async()=>{const c=await ctx();const r=await c.h.services.phase5.saveCommunication({...communication(c.client.id,c.engagement.id,c.assistant.id),status:'Final'},'Tester');await expect(c.h.services.phase5.saveCommunication({...r,summary:'Changed'},'Tester',r.id)).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('319 completed follow-up requires comment and date',async()=>{const c=await ctx();await expect(c.h.services.phase5.saveFollowUp({...followup(c.client.id,c.engagement.id,c.assistant.id),status:'Completed'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('320 overdue follow-up is calculated',async()=>{const c=await ctx();await c.h.services.phase5.saveFollowUp({...followup(c.client.id,c.engagement.id,c.assistant.id),dueDate:old},'Tester');expect((await c.h.services.phase5.listFollowUps())[0].status).toBe('Overdue')});
 it('321 inactive owner is rejected',async()=>{const c=await ctx();const s=await c.h.repositories.staff.getById(c.assistant.id);await c.h.repositories.staff.update({...s!,isActive:false,status:'Inactive'});await expect(c.h.services.phase5.saveFollowUp(followup(c.client.id,c.engagement.id,c.assistant.id),'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('322 billing summary uses actual records',async()=>{const c=await ctx();const i=await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');expect((await c.h.services.phase5.getBillingSummary()).totalOutstanding).toBe(0);let x=await c.h.services.phase5.saveInvoice({...i,status:'Review Pending'},'Tester',i.id);x=await c.h.services.phase5.saveInvoice({...x,status:'Approved',reviewerId:c.reviewer.id,approvalDate:yesterday},'Tester',x.id);x=await c.h.services.phase5.saveInvoice({...x,status:'Issued',issueDate:yesterday},'Tester',x.id);expect((await c.h.services.phase5.getBillingSummary()).totalOutstanding).toBe(1050)});
 it('323 client report includes billing and communications',async()=>{const c=await ctx();await c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester');await c.h.services.phase5.saveCommunication(communication(c.client.id,c.engagement.id,c.assistant.id),'Tester');const r=await c.h.services.phase5.clientReport(c.client.id);expect(r.invoices).toHaveLength(1);expect(r.communications).toHaveLength(1)});
 it('324 dashboard includes Phase 5 indicators',async()=>{const c=await ctx();let r=await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');await c.h.services.phase5.saveTimesheet({...r,status:'Submitted'},'Tester',r.id);const s=await c.h.services.dashboard.getSummary({period:'',partnerId:'',managerId:'',service:'',clientType:'',engagementStatus:''},14);expect(s.timesheetsAwaitingReview).toBe(1)});
 it('325 locked engagement blocks timesheets expenses invoices communications and follow-ups',async()=>{const c=await ctx();const e=await c.h.repositories.engagements.getById(c.engagement.id);await c.h.repositories.engagements.update({...e!,status:'Locked',recordVersion:e!.recordVersion+1});for(const action of [()=>c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester'),()=>c.h.services.phase5.saveExpense(expense(c.assistant.id,c.engagement.id),'Tester'),()=>c.h.services.phase5.saveInvoice(invoice(c.client.id,c.engagement.id,c.assistant.id),'Tester'),()=>c.h.services.phase5.saveCommunication(communication(c.client.id,c.engagement.id,c.assistant.id),'Tester'),()=>c.h.services.phase5.saveFollowUp(followup(c.client.id,c.engagement.id,c.assistant.id),'Tester')])await expect(action()).rejects.toMatchObject({code:'VALIDATION_ERROR'})});
 it('326 Phase 5 changes are activity logged',async()=>{const c=await ctx();const r=await c.h.services.phase5.saveTimesheet(timesheet(c.assistant.id,c.engagement.id),'Tester');expect((await c.h.services.activity.forEntity('Timesheet',r.id)).length).toBe(1)});
 it('327 full backup includes Phase 5 modules in current schema 7.0',async()=>{const c=await ctx();const b=c.h.services.backup.createBackup();expect(b.schemaVersion).toBe('7.0');for(const k of [STORAGE_KEYS.timesheets,STORAGE_KEYS.expenses,STORAGE_KEYS.invoices,STORAGE_KEYS.collections,STORAGE_KEYS.communications,STORAGE_KEYS.followUps])expect(b.data).toHaveProperty(k)});
 it('328 backup rejects invalid Phase 5 relationship',async()=>{const c=await ctx();const b=c.h.services.backup.createBackup();b.data[STORAGE_KEYS.timesheets]=[{id:'x',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),createdByName:'T',updatedByName:'T',recordVersion:1,isDeleted:false,status:'Draft',staffId:'missing',engagementId:c.engagement.id,activityCode:'A',activityType:'Client Work',workDate:yesterday,hours:1,description:'x',billable:true,reviewerId:'',reviewDate:'',returnReason:'',notes:''}];expect(c.h.services.backup.preview(b,'replace').valid).toBe(false)});
 it('329 atomic restore rolls back Phase 5 write failure',async()=>{const source=await ctx();await source.h.services.phase5.saveTimesheet(timesheet(source.assistant.id,source.engagement.id),'Tester');const backup=source.h.services.backup.createBackup();const storage=new FailOnceStorage();const target=createHarness(storage);storage.failKey=STORAGE_KEYS.timesheets;storage.armed=true;const before=storage.getItem(STORAGE_KEYS.clients);const result=await target.services.backup.restore(backup,'replace','Tester');expect(result.rolledBack).toBe(true);expect(storage.getItem(STORAGE_KEYS.clients)).toBe(before)});
 it('330 unsupported schema 5.0 is rejected precisely',async()=>{const c=await ctx();const b=c.h.services.backup.createBackup();b.schemaVersion='5.0';b.settings.schemaVersion='5.0';b.meta.schemaVersion='5.0';const p=c.h.services.backup.preview(b);expect(p.valid).toBe(false);expect(p.errors.join(' ')).toContain('Phase 4')});
});
