import { describe, expect, it } from 'vitest';
import { createHarness, MemoryStorage, seedActiveClient, seedEngagement, seedStaff } from './harness';
import { emptyEngagement } from '../constants/defaults';
import { STORAGE_KEYS } from '../repositories/localStorage/keys';
import type { IStorageGateway } from '../repositories/interfaces/IStorageGateway';

const day='2026-06-20';
class FailOnceStorage extends MemoryStorage { failKey=''; armed=false; override setItem(key:string,value:string){if(this.armed&&key===this.failKey){this.armed=false;throw new Error(`Injected failure ${key}`);}super.setItem(key,value);} }
async function listedContext(){
 const h=createHarness();const client=await seedActiveClient(h,{clientCode:'CL-LPIE',legalName:'Listed Entity',isListedPie:true});const partner=await seedStaff(h,'Partner','P-LPIE');const manager=await seedStaff(h,'Manager','M-LPIE');const qr=await seedStaff(h,'Quality Reviewer','Q-LPIE');
 const engagement=await h.services.engagements.create({...emptyEngagement,engagementCode:'ENG-LPIE',clientId:client.id,serviceType:'Audit',engagementType:'Listed Statutory Audit',responsiblePartnerId:partner.id,responsibleManagerId:manager.id,listedPieWorkflowRequired:true,status:'Draft'},'Tester');return{h,client,partner,manager,qr,engagement};
}
async function serviceContext(service:'Tax'|'VAT'|'RJSC'|'Accounting'|'Advisory'){
 const h=createHarness();const client=await seedActiveClient(h,{clientCode:`CL-${service}`,legalName:`${service} Client`});const partner=await seedStaff(h,'Partner',`P-${service}`);const manager=await seedStaff(h,'Manager',`M-${service}`);const assistant=await seedStaff(h,'Assistant',`A-${service}`);const engagement=await h.services.engagements.create({...emptyEngagement,engagementCode:`ENG-${service}`,clientId:client.id,serviceType:service,engagementType:`${service} Assignment`,responsiblePartnerId:partner.id,responsibleManagerId:manager.id,status:'Draft'},'Tester');return{h,client,partner,manager,assistant,engagement};
}
const compliance=(engagementId:string)=>({engagementId,checklistCode:'L-1',requirement:'Requirement',category:'Quality',ownerId:'',dueDate:'',required:true,evidenceReference:'',completionComment:'',completedById:'',completionDate:'',reviewerId:'',reviewDate:'',status:'Not Started' as const,exceptionReason:'',notApplicableReason:'',notes:''});
const eqr=(engagementId:string,qualityReviewerId:string)=>({engagementId,qualityReviewerId,reviewStartDate:day,reviewCompletionDate:'',significantJudgementsReviewed:false,significantRisksReviewed:false,materialityReviewed:false,independenceReviewed:false,goingConcernReviewed:false,keyAuditMattersReviewed:false,financialStatementsReviewed:false,auditOpinionReviewed:false,uncorrectedMisstatementsReviewed:false,reviewFindings:'',reviewerConclusion:'',managerResponse:'',partnerResponse:'',status:'Planned' as const,approvalDate:'',waiverReason:'',notes:''});

describe('Complete Phase 4 services',()=>{
 it('242 blocks Listed workspace for normal audit',async()=>{const h=createHarness();const e=await seedEngagement(h);await expect(h.services.phase4.initializeListedChecklist(e.id,'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('243 allows Listed workspace from client/engagement flag',async()=>{const c=await listedContext();expect((await c.h.services.phase4.initializeListedChecklist(c.engagement.id,'Tester')).length).toBe(18);});
 it('244 initializes exact approved 18-area checklist once',async()=>{const c=await listedContext();await c.h.services.phase4.initializeListedChecklist(c.engagement.id,'Tester');expect((await c.h.services.phase4.initializeListedChecklist(c.engagement.id,'Tester')).length).toBe(18);});
 it('245 Not Applicable compliance requires reason',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveListedCompliance({...compliance(c.engagement.id),status:'Not Applicable'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('246 compliance Exception requires reason',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveListedCompliance({...compliance(c.engagement.id),status:'Exception'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('247 compliance completion requires evidence or comment',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveListedCompliance({...compliance(c.engagement.id),status:'Completed'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('248 regulatory overdue is calculated automatically',async()=>{const c=await listedContext();const r=await c.h.services.phase4.saveRegulatoryDeadline({clientId:c.client.id,engagementId:c.engagement.id,regulatoryBody:'BSEC',requirement:'Filing',reportingPeriod:'2025',dueDate:'2020-01-01',responsiblePersonId:c.manager.id,priority:'Critical',status:'Upcoming',submissionCompletionDate:'',reference:'',changeReason:'',notes:''},'Tester');expect(c.h.services.phase4.computedDeadlineStatus(r)).toBe('Overdue');});
 it('249 critical regulatory due-date change requires reason',async()=>{const c=await listedContext();const r=await c.h.services.phase4.saveRegulatoryDeadline({clientId:c.client.id,engagementId:c.engagement.id,regulatoryBody:'BSEC',requirement:'Filing',reportingPeriod:'2025',dueDate:'2026-07-01',responsiblePersonId:c.manager.id,priority:'Critical',status:'Upcoming',submissionCompletionDate:'',reference:'',changeReason:'',notes:''},'Tester');await expect(c.h.services.phase4.saveRegulatoryDeadline({...r,dueDate:'2026-07-02'},'Tester',r.id)).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('250 submitted regulatory deadline requires date',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveRegulatoryDeadline({clientId:c.client.id,engagementId:c.engagement.id,regulatoryBody:'BSEC',requirement:'Filing',reportingPeriod:'2025',dueDate:day,responsiblePersonId:c.manager.id,priority:'High',status:'Submitted',submissionCompletionDate:'',reference:'',changeReason:'',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('251 communicated Audit Committee record requires date and recipient',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveCommitteeCommunication({engagementId:c.engagement.id,communicationReference:'AC-1',communicationStage:'Completion',communicationDate:'',meetingDate:'',recipient:'',subject:'Completion',significantRisksCommunicated:true,independenceCommunicated:true,uncorrectedMisstatementsCommunicated:true,controlDeficienciesCommunicated:true,keyAuditMattersDiscussed:true,goingConcernDiscussed:true,followUpActions:'',responsiblePersonId:c.manager.id,status:'Communicated',fileReference:'',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('252 Audit Committee reference is unique',async()=>{const c=await listedContext();const x={engagementId:c.engagement.id,communicationReference:'AC-1',communicationStage:'Planning' as const,communicationDate:day,meetingDate:'',recipient:'Committee',subject:'Plan',significantRisksCommunicated:true,independenceCommunicated:true,uncorrectedMisstatementsCommunicated:false,controlDeficienciesCommunicated:false,keyAuditMattersDiscussed:false,goingConcernDiscussed:false,followUpActions:'',responsiblePersonId:c.manager.id,status:'Communicated' as const,fileReference:'',notes:''};await c.h.services.phase4.saveCommitteeCommunication(x,'Tester');await expect(c.h.services.phase4.saveCommitteeCommunication(x,'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('253 EQR reviewer must have Quality Reviewer role',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveQualityReview(eqr(c.engagement.id,c.manager.id),'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('254 EQR reviewer cannot be engagement Partner or Manager',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveQualityReview(eqr(c.engagement.id,c.manager.id),'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});await expect(c.h.services.phase4.saveQualityReview(eqr(c.engagement.id,c.partner.id),'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('255 Review Complete EQR requires all mandatory areas',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveQualityReview({...eqr(c.engagement.id,c.qr.id),status:'Review Complete'},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('256 Cleared EQR requires conclusion and completion date',async()=>{const c=await listedContext();const x=eqr(c.engagement.id,c.qr.id);await expect(c.h.services.phase4.saveQualityReview({...x,status:'Cleared',significantJudgementsReviewed:true,significantRisksReviewed:true,materialityReviewed:true,independenceReviewed:true,goingConcernReviewed:true,keyAuditMattersReviewed:true,financialStatementsReviewed:true,auditOpinionReviewed:true,uncorrectedMisstatementsReviewed:true},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('257 valid Cleared EQR saves',async()=>{const c=await listedContext();const x=eqr(c.engagement.id,c.qr.id);const saved=await c.h.services.phase4.saveQualityReview({...x,status:'Cleared',reviewCompletionDate:day,reviewerConclusion:'Cleared',significantJudgementsReviewed:true,significantRisksReviewed:true,materialityReviewed:true,independenceReviewed:true,goingConcernReviewed:true,keyAuditMattersReviewed:true,financialStatementsReviewed:true,auditOpinionReviewed:true,uncorrectedMisstatementsReviewed:true},'Tester');expect(saved.status).toBe('Cleared');});
 it('258 Not a KAM requires reason',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveKam({engagementId:c.engagement.id,kamReference:'K-1',title:'Matter',relatedSignificantRiskId:'',whyMatterWasSignificant:'',howMatterWasAddressed:'',relatedWorkingPaperIds:[],auditCommitteeDiscussionReference:'',proposedReportWording:'',managerReviewerId:c.manager.id,partnerApproverId:c.partner.id,qualityReviewerId:c.qr.id,status:'Not a KAM',decisionReason:'',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('259 KAM significant risk relationship is enforced',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveKam({engagementId:c.engagement.id,kamReference:'K-1',title:'Matter',relatedSignificantRiskId:'missing',whyMatterWasSignificant:'',howMatterWasAddressed:'',relatedWorkingPaperIds:[],auditCommitteeDiscussionReference:'',proposedReportWording:'',managerReviewerId:c.manager.id,partnerApproverId:c.partner.id,qualityReviewerId:c.qr.id,status:'Draft',decisionReason:'',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('260 approved KAM requires Partner',async()=>{const c=await listedContext();await expect(c.h.services.phase4.saveKam({engagementId:c.engagement.id,kamReference:'K-1',title:'Matter',relatedSignificantRiskId:'',whyMatterWasSignificant:'',howMatterWasAddressed:'',relatedWorkingPaperIds:[],auditCommitteeDiscussionReference:'',proposedReportWording:'',managerReviewerId:c.manager.id,partnerApproverId:'',qualityReviewerId:c.qr.id,status:'Approved',decisionReason:'',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('261 Listed readiness returns exact blockers',async()=>{const c=await listedContext();const r=await c.h.services.phase4.listedReadiness(c.engagement.id);expect(r.blockingItems.some(x=>x.includes('Checklist'))).toBe(true);expect(r.blockingItems.some(x=>x.includes('Quality Review'))).toBe(true);});
 it('262 normal audit has no additional Listed blockers',async()=>{const h=createHarness();const e=await seedEngagement(h);expect((await h.services.phase4.listedReadiness(e.id)).blockingItems).toEqual([]);});
 it('263 Tax requires assessment year and filing deadline',async()=>{const c=await serviceContext('Tax');await expect(c.h.services.phase4.saveTax({engagementId:c.engagement.id,assessmentYear:'',taxAssignmentType:'Income Tax Return',taxpayerTin:'',filingDeadline:'',documentsRequired:'',computationVersion:'',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',assessmentHearingDate:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Draft',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('264 Tax Submitted requires client confirmation and reference',async()=>{const c=await serviceContext('Tax');await expect(c.h.services.phase4.saveTax({engagementId:c.engagement.id,assessmentYear:'2026',taxAssignmentType:'Income Tax Return',taxpayerTin:'',filingDeadline:day,documentsRequired:'',computationVersion:'1',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',managerReviewDate:day,submissionDate:day,submissionReference:'',assessmentHearingDate:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Submitted',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('265 Tax submission chronology is enforced',async()=>{const c=await serviceContext('Tax');await expect(c.h.services.phase4.saveTax({engagementId:c.engagement.id,assessmentYear:'2026',taxAssignmentType:'Income Tax Return',taxpayerTin:'',filingDeadline:day,documentsRequired:'',computationVersion:'1',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'2026-06-20',managerReviewDate:'2026-06-20',submissionDate:'2026-06-19',submissionReference:'T-1',assessmentHearingDate:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Submitted',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('266 VAT net calculation is enforced',async()=>{const c=await serviceContext('VAT');await expect(c.h.services.phase4.saveVat({engagementId:c.engagement.id,vatPeriod:'May 2026',bin:'BIN',assignmentType:'Periodic VAT Return',filingDeadline:day,outputVat:100,inputVat:40,adjustments:5,netVatPayableRefundable:1,reconciliationStatus:'',clientApprovalDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',noticeReference:'',noticeResponseDeadline:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Draft',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('267 VAT submission requires approval and reference',async()=>{const c=await serviceContext('VAT');await expect(c.h.services.phase4.saveVat({engagementId:c.engagement.id,vatPeriod:'May 2026',bin:'BIN',assignmentType:'Periodic VAT Return',filingDeadline:day,outputVat:100,inputVat:40,adjustments:5,netVatPayableRefundable:65,reconciliationStatus:'',clientApprovalDate:'',managerReviewDate:'',submissionDate:day,submissionReference:'',noticeReference:'',noticeResponseDeadline:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Submitted',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('268 RJSC requires registration, filing type and period',async()=>{const c=await serviceContext('RJSC');await expect(c.h.services.phase4.saveRjsc({engagementId:c.engagement.id,companyRegistrationNumber:'',filingType:'',filingPeriod:'',filingDeadline:'',documentsRequired:'',clientSignOffDate:'',filingDate:'',filingReference:'',acceptanceDate:'',responsibleStaffId:c.assistant.id,reviewerId:c.manager.id,status:'Draft',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('269 RJSC Filed requires client sign-off, date and reference',async()=>{const c=await serviceContext('RJSC');await expect(c.h.services.phase4.saveRjsc({engagementId:c.engagement.id,companyRegistrationNumber:'R-1',filingType:'Annual Return',filingPeriod:'2025',filingDeadline:day,documentsRequired:'',clientSignOffDate:'',filingDate:'',filingReference:'',acceptanceDate:'',responsibleStaffId:c.assistant.id,reviewerId:c.manager.id,status:'Filed',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('270 Accounting period chronology is enforced',async()=>{const c=await serviceContext('Accounting');await expect(c.h.services.phase4.saveAccounting({engagementId:c.engagement.id,accountingPeriodStart:'2026-12-31',accountingPeriodEnd:'2026-01-01',scope:'Bookkeeping',openingBalanceConfirmed:false,recordsReceived:false,processingStatus:'',bankReconciliationStatus:'',unreconciledItems:'',trialBalanceStatus:'',draftAccountsVersion:'',clientReviewDate:'',finalAccountsVersion:'',responsibleStaffId:c.assistant.id,reviewerId:c.manager.id,reviewerApprovalDate:'',status:'Draft',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('271 Accounting Finalised requires controls and output',async()=>{const c=await serviceContext('Accounting');await expect(c.h.services.phase4.saveAccounting({engagementId:c.engagement.id,accountingPeriodStart:'2026-01-01',accountingPeriodEnd:'2026-12-31',scope:'Bookkeeping',openingBalanceConfirmed:false,recordsReceived:true,processingStatus:'',bankReconciliationStatus:'',unreconciledItems:'Pending',trialBalanceStatus:'',draftAccountsVersion:'',clientReviewDate:'',finalAccountsVersion:'',responsibleStaffId:c.assistant.id,reviewerId:'',reviewerApprovalDate:'',status:'Finalised',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('272 Advisory requires scope and deliverables',async()=>{const c=await serviceContext('Advisory');await expect(c.h.services.phase4.saveAdvisory({engagementId:c.engagement.id,advisoryType:'Due Diligence',scope:'',exclusions:'',deliverables:'',milestones:'',budgetAmount:0,budgetHours:0,responsiblePartnerId:c.partner.id,responsibleManagerId:c.manager.id,clientAcceptanceDate:'',draftDeliverableReference:'',internalReviewDate:'',clientPresentationDate:'',finalDeliverableReference:'',status:'Proposal',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('273 Advisory Approved requires client acceptance',async()=>{const c=await serviceContext('Advisory');await expect(c.h.services.phase4.saveAdvisory({engagementId:c.engagement.id,advisoryType:'Due Diligence',scope:'Scope',exclusions:'',deliverables:'Report',milestones:'',budgetAmount:0,budgetHours:0,responsiblePartnerId:c.partner.id,responsibleManagerId:c.manager.id,clientAcceptanceDate:'',draftDeliverableReference:'',internalReviewDate:'',clientPresentationDate:'',finalDeliverableReference:'',status:'Approved',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('274 Advisory Final Deliverable requires reference',async()=>{const c=await serviceContext('Advisory');await expect(c.h.services.phase4.saveAdvisory({engagementId:c.engagement.id,advisoryType:'Due Diligence',scope:'Scope',exclusions:'',deliverables:'Report',milestones:'',budgetAmount:0,budgetHours:0,responsiblePartnerId:c.partner.id,responsibleManagerId:c.manager.id,clientAcceptanceDate:day,draftDeliverableReference:'D1',internalReviewDate:day,clientPresentationDate:day,finalDeliverableReference:'',status:'Final Deliverable',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('275 service-specific workspace rejects another service',async()=>{const c=await serviceContext('Tax');await expect(c.h.services.phase4.saveVat({engagementId:c.engagement.id,vatPeriod:'May',bin:'B',assignmentType:'Return',filingDeadline:day,outputVat:0,inputVat:0,adjustments:0,netVatPayableRefundable:0,reconciliationStatus:'',clientApprovalDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',noticeReference:'',noticeResponseDeadline:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Draft',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('276 Locked engagement blocks Phase 4 service mutation',async()=>{const c=await serviceContext('Tax');const e=await c.h.repositories.engagements.getById(c.engagement.id);await c.h.repositories.engagements.update({...e!,status:'Locked',recordVersion:e!.recordVersion+1});await expect(c.h.services.phase4.saveTax({engagementId:c.engagement.id,assessmentYear:'2026',taxAssignmentType:'Return',taxpayerTin:'',filingDeadline:day,documentsRequired:'',computationVersion:'',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',assessmentHearingDate:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Draft',notes:''},'Tester')).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
 it('277 Phase 4 changes are activity logged',async()=>{const c=await listedContext();const item=await c.h.services.phase4.saveListedCompliance(compliance(c.engagement.id),'Tester');expect((await c.h.services.activity.forEntity('Listed Compliance Item',item.id)).length).toBe(1);});
 it('278 Dashboard includes Phase 4 indicators',async()=>{const c=await serviceContext('Tax');await c.h.services.phase4.saveTax({engagementId:c.engagement.id,assessmentYear:'2026',taxAssignmentType:'Return',taxpayerTin:'',filingDeadline:'2020-01-01',documentsRequired:'',computationVersion:'',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',assessmentHearingDate:'',responsibleStaffId:c.assistant.id,managerReviewerId:c.manager.id,status:'Draft',notes:''},'Tester');const s=await c.h.services.dashboard.getSummary({period:'',partnerId:'',managerId:'',service:'',clientType:'',engagementStatus:''},14);expect(s.taxSubmissionsOverdue).toBe(1);});
 it('279 full backup includes Phase 4 modules in current schema 7.0',async()=>{const c=await listedContext();const b=c.h.services.backup.createBackup();expect(b.schemaVersion).toBe('7.0');for(const k of [STORAGE_KEYS.listedComplianceItems,STORAGE_KEYS.regulatoryDeadlines,STORAGE_KEYS.auditCommitteeCommunications,STORAGE_KEYS.qualityReviews,STORAGE_KEYS.keyAuditMatters,STORAGE_KEYS.taxAssignments,STORAGE_KEYS.vatAssignments,STORAGE_KEYS.rjscAssignments,STORAGE_KEYS.accountingAssignments,STORAGE_KEYS.advisoryAssignments])expect(b.data).toHaveProperty(k);});
 it('280 backup rejects invalid Phase 4 relationship',async()=>{const c=await listedContext();const b=c.h.services.backup.createBackup();b.data[STORAGE_KEYS.taxAssignments]=[{id:'x',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),createdByName:'T',updatedByName:'T',recordVersion:1,isDeleted:false,status:'Draft',engagementId:c.engagement.id,assessmentYear:'2026',taxAssignmentType:'Return',taxpayerTin:'',filingDeadline:day,documentsRequired:'',computationVersion:'',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',assessmentHearingDate:'',responsibleStaffId:'',managerReviewerId:'',notes:''}];expect(c.h.services.backup.preview(b,'replace').valid).toBe(false);});
 it('281 atomic restore rolls back Phase 4 module write failure',async()=>{const source=await serviceContext('Tax');await source.h.services.phase4.saveTax({engagementId:source.engagement.id,assessmentYear:'2026',taxAssignmentType:'Return',taxpayerTin:'',filingDeadline:day,documentsRequired:'',computationVersion:'',taxableIncome:0,taxLiability:0,advanceTax:0,withholdingTax:0,taxPayableRefundable:0,clientConfirmationDate:'',managerReviewDate:'',submissionDate:'',submissionReference:'',assessmentHearingDate:'',responsibleStaffId:source.assistant.id,managerReviewerId:source.manager.id,status:'Draft',notes:''},'Tester');const backup=source.h.services.backup.createBackup();const storage=new FailOnceStorage();const target=createHarness(storage);storage.failKey=STORAGE_KEYS.taxAssignments;storage.armed=true;const before=storage.getItem(STORAGE_KEYS.clients);const result=await target.services.backup.restore(backup,'replace','Tester');expect(result.rolledBack).toBe(true);expect(storage.getItem(STORAGE_KEYS.clients)).toBe(before);});
 it('282 unsupported schema 4.0 is rejected with migration message',async()=>{const c=await listedContext();const b=c.h.services.backup.createBackup();b.schemaVersion='4.0';b.settings.schemaVersion='4.0';b.meta.schemaVersion='4.0';const p=c.h.services.backup.preview(b);expect(p.valid).toBe(false);expect(p.errors.join(' ')).toContain('Phase 3');});
});
