import type { RepositoryRegistry } from '../repositories';
import type { ManagerReviewRecord, PartnerReviewRecord } from '../types/models';
import { AppError, ValidationError } from '../utils/errors';
import { createMetadata, updateMetadata } from './helpers';
import { requireMutableEngagement } from './engagementLock';
import type { ActivityService } from './ActivityService';
import type { AuditCompletionService } from './AuditCompletionService';
import type { AuditFindingService } from './AuditFindingService';
import { getListedGateBlockers } from './Phase4Service';

export interface ReviewReadiness { percentage:number; completedCriteria:number; totalCriteria:number; blockingItems:string[]; }
export type ManagerReviewInput=Omit<ManagerReviewRecord,'id'|'createdAt'|'updatedAt'|'createdByName'|'updatedByName'|'recordVersion'|'isDeleted'|'readinessPercentage'|'blockingItems'>;
export type PartnerReviewInput=Omit<PartnerReviewRecord,'id'|'createdAt'|'updatedAt'|'createdByName'|'updatedByName'|'recordVersion'|'isDeleted'|'readinessPercentage'|'blockingItems'>;
export class AuditReviewWorkflowService{
 constructor(private readonly repositories:RepositoryRegistry,private readonly activity:ActivityService,private readonly completion:AuditCompletionService,private readonly findings:AuditFindingService){}
 async managerRecord(engagementId:string){return (await this.repositories.managerReviewRecords.list({includeDeleted:true})).find(r=>r.engagementId===engagementId&&!r.isDeleted)??null;}
 async partnerRecord(engagementId:string){return (await this.repositories.partnerReviewRecords.list({includeDeleted:true})).find(r=>r.engagementId===engagementId&&!r.isDeleted)??null;}
 async managerReadiness(engagementId:string):Promise<ReviewReadiness>{
  const blockers:string[]=[]; const programmes=(await this.repositories.engagementProgrammes.list()).filter(p=>p.engagementId===engagementId); const mandatory=programmes.filter(p=>p.mandatory); if(!mandatory.length) blockers.push('No mandatory Audit Programme procedures exist.'); else for(const p of mandatory) if(!['Completed','Reviewed'].includes(p.status)) blockers.push(`Mandatory procedure ${p.procedureCode} is not completed/reviewed.`);
  const wps=(await this.repositories.workingPapers.list()).filter(w=>w.engagementId===engagementId); if(!wps.length) blockers.push('No Working Papers have been prepared.'); else for(const w of wps) if(['Draft','In Preparation','Prepared','Rework'].includes(w.status)) blockers.push(`Working Paper ${w.wpReference} is not submitted/cleared.`);
  const notes=(await this.repositories.reviewNotes.list()).filter(n=>n.engagementId===engagementId&&n.reviewLevel==='Manager'&&['Critical','High'].includes(n.severity)&&!['Cleared','Cancelled'].includes(n.status)); if(notes.length) blockers.push(`${notes.length} Critical/High Manager review note(s) remain unresolved.`);
  const materiality=(await this.repositories.auditMateriality.list()).filter(m=>m.engagementId===engagementId&&m.status==='Approved'); if(!materiality.length) blockers.push('Approved Materiality is required.');
  const risks=(await this.repositories.auditRisks.list()).filter(r=>r.engagementId===engagementId&&(r.significantRisk||r.fraudRisk)); for(const r of risks) if(r.status!=='Approved'||!r.plannedAuditResponse.trim()) blockers.push(`Significant/Fraud Risk ${r.riskCode} is not appropriately addressed.`);
  const evidence=(await this.repositories.evidenceRegister.list()).filter(e=>e.engagementId===engagementId&&e.status==='Accepted'); for(const w of wps.filter(w=>!['Draft','In Preparation'].includes(w.status))) if(!evidence.some(e=>e.workingPaperId===w.id)) blockers.push(`Working Paper ${w.wpReference} has no accepted evidence.`);
  const total=Math.max(6+mandatory.length+wps.length+risks.length,1); const completed=Math.max(total-blockers.length,0); return {percentage:Math.round(completed/total*100),completedCriteria:completed,totalCriteria:total,blockingItems:blockers};
 }
 async partnerReadiness(engagementId:string):Promise<ReviewReadiness>{
  const blockers:string[]=[]; const manager=await this.managerRecord(engagementId); if(!manager||manager.status!=='Completed') blockers.push('Manager Review must be completed first.');
  const notes=(await this.repositories.reviewNotes.list()).filter(n=>n.engagementId===engagementId&&['Critical','High'].includes(n.severity)&&!['Cleared','Cancelled'].includes(n.status)); if(notes.length) blockers.push(`${notes.length} Critical/High review note(s) remain unresolved.`);
  blockers.push(...await this.completion.blockers(engagementId,['ACP-18']));
  const reports=(await this.repositories.reportVersions.list()).filter(r=>r.engagementId===engagementId&&!r.isDeleted); if(!reports.some(r=>r.finalVersion&&r.status==='Final Approved')) blockers.push('A Final Approved report version must be selected.');
  const material=await this.findings.unresolvedMaterial(engagementId); if(material.length) blockers.push(`${material.length} unresolved material misstatement(s) remain.`);
  blockers.push(...await getListedGateBlockers(this.repositories,engagementId));
  const total=5+Math.max((await getListedGateBlockers(this.repositories,engagementId)).length,0); const completed=Math.max(total-blockers.length,0); return {percentage:Math.round(completed/total*100),completedCriteria:completed,totalCriteria:total,blockingItems:blockers};
 }
 async saveManager(input:ManagerReviewInput,operatorName:string,id?:string):Promise<ManagerReviewRecord>{
  await requireMutableEngagement(this.repositories.engagements,this.activity,input.engagementId,operatorName,'manager review mutation'); const readiness=await this.managerReadiness(input.engagementId); const existing=id?await this.repositories.managerReviewRecords.getById(id):await this.managerRecord(input.engagementId); const errors:string[]=[];
  if(input.status==='Completed'){if(readiness.blockingItems.length) errors.push(...readiness.blockingItems); if(!input.managerId||!input.completionDate) errors.push('Manager and Completion Date are required.');}
  if(input.status==='Reopened'&&!input.reopenReason.trim()) errors.push('Reopening Manager Review requires a reason.'); if(input.status==='Returned'&&!input.returnComment.trim()) errors.push('Returning an area requires a comment.'); if(errors.length) throw new ValidationError('Manager Review could not be completed.',errors);
  const payload={...input,readinessPercentage:readiness.percentage,blockingItems:readiness.blockingItems}; const record:ManagerReviewRecord=existing?updateMetadata({...existing,...payload},operatorName):{...payload,...createMetadata(input.status,operatorName),status:input.status}; const saved=existing?await this.repositories.managerReviewRecords.update(record):await this.repositories.managerReviewRecords.create(record); await this.activity.log({entityType:'Manager Review',entityId:saved.id,action:'Review Action',previousStatus:existing?.status,newStatus:saved.status,operatorName,reason:saved.reopenReason||saved.returnComment,changedFieldSummary:`Manager review readiness ${readiness.percentage}%`}); return saved;
 }
 async savePartner(input:PartnerReviewInput,operatorName:string,id?:string):Promise<PartnerReviewRecord>{
  await requireMutableEngagement(this.repositories.engagements,this.activity,input.engagementId,operatorName,'partner review mutation'); const readiness=await this.partnerReadiness(input.engagementId); const existing=id?await this.repositories.partnerReviewRecords.getById(id):await this.partnerRecord(input.engagementId); const errors:string[]=[]; const manager=await this.managerRecord(input.engagementId);
  if(['Approved','Completed'].includes(input.status)){if(readiness.blockingItems.length) errors.push(...readiness.blockingItems); if(!input.partnerId||!input.approvalDate||!input.selectedReportVersionId) errors.push('Partner, Approval Date and selected Final Report Version are required.'); if(!input.decisionComment.trim()) errors.push('Partner approval requires a decision comment.'); if(manager?.completionDate&&input.approvalDate<manager.completionDate) errors.push('Partner Approval Date cannot precede Manager Review completion date.'); const selected=await this.repositories.reportVersions.getById(input.selectedReportVersionId); if(selected&&input.partnerId===selected.managerReviewerId) errors.push('Partner cannot approve work they prepared/reviewed as Manager.');}
  if(['Returned','Rejected'].includes(input.status)&&!input.decisionComment.trim()) errors.push('Return/rejection requires a decision comment.'); if(input.status==='Reopened'&&!input.reopenReason.trim()) errors.push('Reopening Partner Approval requires a reason.'); if(errors.length) throw new ValidationError('Partner Review could not be saved.',errors);
  const payload={...input,readinessPercentage:readiness.percentage,blockingItems:readiness.blockingItems}; const record:PartnerReviewRecord=existing?updateMetadata({...existing,...payload},operatorName):{...payload,...createMetadata(input.status,operatorName),status:input.status}; const saved=existing?await this.repositories.partnerReviewRecords.update(record):await this.repositories.partnerReviewRecords.create(record); if(['Approved','Completed'].includes(saved.status)){const item=(await this.repositories.auditCompletionItems.list()).find(i=>i.engagementId===saved.engagementId&&i.checklistCode==='ACP-18'&&!i.isDeleted);if(item&&!['Completed','Reviewed'].includes(item.status))await this.repositories.auditCompletionItems.update(updateMetadata({...item,status:'Completed' as const,evidenceReference:`Partner Review ${saved.id}`,completionComment:'Partner approval completed.',completedById:saved.partnerId,completionDate:saved.approvalDate},operatorName));}
  await this.activity.log({entityType:'Partner Review',entityId:saved.id,action:'Approval',previousStatus:existing?.status,newStatus:saved.status,operatorName,reason:saved.decisionComment||saved.reopenReason,changedFieldSummary:`Partner review readiness ${readiness.percentage}%`}); return saved;
 }
}
