import type { RepositoryRegistry } from '../repositories';
import type { AuditReportVersion, FinalReportIssue, ManagementLetter, RepresentationLetter } from '../types/models';
import { AppError, ValidationError } from '../utils/errors';
import { summarizeChanges } from '../utils/changeSummary';
import { createMetadata, updateMetadata } from './helpers';
import { requireMutableEngagement } from './engagementLock';
import type { ActivityService } from './ActivityService';
import { getListedGateBlockers } from './Phase4Service';

export type ReportVersionInput=Omit<AuditReportVersion,'id'|'createdAt'|'updatedAt'|'createdByName'|'updatedByName'|'recordVersion'|'isDeleted'>;
export type ManagementLetterInput=Omit<ManagementLetter,'id'|'createdAt'|'updatedAt'|'createdByName'|'updatedByName'|'recordVersion'|'isDeleted'>;
export type RepresentationLetterInput=Omit<RepresentationLetter,'id'|'createdAt'|'updatedAt'|'createdByName'|'updatedByName'|'recordVersion'|'isDeleted'>;
export type ReportIssueInput=Omit<FinalReportIssue,'id'|'createdAt'|'updatedAt'|'createdByName'|'updatedByName'|'recordVersion'|'isDeleted'>;

const reportTransitions:Record<AuditReportVersion['status'],AuditReportVersion['status'][]>= {Draft:['Manager Review','Withdrawn'],'Manager Review':['Returned','Partner Review'],'Returned':['Draft','Manager Review'],'Partner Review':['Returned','Final Approved'],'Final Approved':['Issued','Superseded','Withdrawn'],Issued:['Superseded','Withdrawn'],Superseded:[],Withdrawn:[]};
export class AuditReportingService{
 constructor(private readonly repositories:RepositoryRegistry,private readonly activity:ActivityService){}
 async reports(engagementId:string){return (await this.repositories.reportVersions.list({includeDeleted:true})).filter(r=>r.engagementId===engagementId);}
 async managementLetters(engagementId:string){return (await this.repositories.managementLetters.list({includeDeleted:true})).filter(r=>r.engagementId===engagementId);}
 async representationLetters(engagementId:string){return (await this.repositories.representationLetters.list({includeDeleted:true})).filter(r=>r.engagementId===engagementId);}
 async issues(engagementId:string){return (await this.repositories.reportIssues.list({includeDeleted:true})).filter(r=>r.engagementId===engagementId);}
 private chronology(manager:string,partner:string,errors:string[]){if(partner&&!manager) errors.push('Manager Review Date is required before Partner Approval Date.'); if(manager&&partner&&partner<manager) errors.push('Partner Approval Date cannot be earlier than Manager Review Date.');}
 async saveReport(input:ReportVersionInput,operatorName:string,id?:string):Promise<AuditReportVersion>{
  await requireMutableEngagement(this.repositories.engagements,this.activity,input.engagementId,operatorName,'audit report version mutation'); const errors:string[]=[];
  if(!input.reportType.trim()||input.versionNumber<1) errors.push('Report Type and positive Version Number are required.'); if(!input.versionDate) errors.push('Version Date is required.');
  this.chronology(input.managerReviewDate,input.partnerApprovalDate,errors); if(input.status==='Returned'&&!input.returnReason.trim()) errors.push('Returned report requires a reason.'); if(input.status==='Final Approved'&&!input.finalVersion) errors.push('Final Approved status requires Final Version to be selected.');
  if(['Partner Review','Final Approved','Issued'].includes(input.status)&&!input.managerReviewDate) errors.push('Manager review must be completed before Partner review.');
  if(['Final Approved','Issued'].includes(input.status)&&(!input.partnerApprovalDate||!input.partnerApproverId)) errors.push('Partner approval is required for Final Approved/Issued report.');
  const all=await this.reports(input.engagementId); if(all.some(r=>!r.isDeleted&&r.reportType.toLowerCase()===input.reportType.toLowerCase()&&r.versionNumber===input.versionNumber&&r.id!==id)) errors.push('Report version must be unique within engagement and report type.');
  const existing=id?await this.repositories.reportVersions.getById(id):null; if(!existing&&input.status!=='Draft') errors.push('A new report version must start in Draft status.'); if(input.status==='Final Approved') errors.push(...await getListedGateBlockers(this.repositories,input.engagementId)); if(errors.length) throw new ValidationError('Audit report version could not be saved.',errors); if(id&&!existing) throw new AppError('Report version not found.','NOT_FOUND'); if(existing&&existing.status!==input.status&&!reportTransitions[existing.status].includes(input.status)) throw new ValidationError('Unsupported report status transition.',[`${existing.status} cannot move directly to ${input.status}.`]);
  const now=new Date().toISOString(); const candidate:AuditReportVersion=existing?updateMetadata({...existing,...input},operatorName):{...input,...createMetadata(input.status,operatorName),status:input.status}; const original=await this.repositories.reportVersions.list({includeDeleted:true});
  const next=original.map(r=>r.id===candidate.id?candidate:r);
  if(!existing) next.push(candidate);
  if(candidate.currentVersion||candidate.finalVersion||candidate.status==='Final Approved') for(let i=0;i<next.length;i++){const r=next[i]; if(r.id!==candidate.id&&r.engagementId===candidate.engagementId&&r.reportType===candidate.reportType&&!r.isDeleted&&((candidate.currentVersion&&r.currentVersion)||(candidate.finalVersion&&r.finalVersion)||(candidate.status==='Final Approved'&&r.status==='Final Approved'))){next[i]={...r,currentVersion:candidate.currentVersion?false:r.currentVersion,finalVersion:candidate.finalVersion||candidate.status==='Final Approved'?false:r.finalVersion,status:candidate.status==='Final Approved'?'Superseded':r.status,updatedAt:now,updatedByName:operatorName,recordVersion:r.recordVersion+1};}}
  try{await this.repositories.reportVersions.replaceAll(next);}catch(error){try{await this.repositories.reportVersions.replaceAll(original);}catch{/* original error preserved */} throw new AppError(`Atomic report version update failed and was rolled back. ${error instanceof Error?error.message:''}`,'ATOMIC_OPERATION_FAILED');}
  await this.activity.log({entityType:'Audit Report Version',entityId:candidate.id,action:existing?'Update':'Create',previousStatus:existing?.status,newStatus:candidate.status,changedFieldSummary:existing?summarizeChanges(existing,candidate):`Report ${candidate.reportType} v${candidate.versionNumber} created`,operatorName,reason:candidate.returnReason}); return candidate;
 }
 async saveManagementLetter(input:ManagementLetterInput,operatorName:string,id?:string):Promise<ManagementLetter>{
  await requireMutableEngagement(this.repositories.engagements,this.activity,input.engagementId,operatorName,'management letter mutation'); const errors:string[]=[]; if(!input.reference.trim()||input.version<1) errors.push('Reference and positive Version are required.'); this.chronology(input.managerReviewDate,input.partnerApprovalDate,errors); if(['Partner Review','Sent to Client','Client Response Received','Final'].includes(input.status)&&(!input.managerReviewerId||!input.managerReviewDate)) errors.push('Manager review is required before Partner review.'); if(['Sent to Client','Client Response Received','Final'].includes(input.status)&&(!input.partnerApproverId||!input.partnerApprovalDate)) errors.push('Partner approval is required before the Management Letter is sent/finalised.');
  const findings=await this.repositories.auditFindings.list({includeDeleted:true}); for(const fid of input.findingIds){const f=findings.find(x=>x.id===fid&&x.engagementId===input.engagementId); if(!f||!f.reportable) errors.push(`Finding ${fid} is missing or not reportable.`);} const all=await this.managementLetters(input.engagementId); if(all.some(r=>!r.isDeleted&&r.version===input.version&&r.id!==id)) errors.push('Management Letter version must be unique within the engagement.'); if(errors.length) throw new ValidationError('Management Letter could not be saved.',errors);
  const existing=id?await this.repositories.managementLetters.getById(id):null; const candidate:ManagementLetter=existing?updateMetadata({...existing,...input},operatorName):{...input,...createMetadata(input.status,operatorName),status:input.status}; const original=await this.repositories.managementLetters.list({includeDeleted:true}); const next=original.map(r=>r.id===candidate.id?candidate:r); if(!existing)next.push(candidate); if(candidate.currentVersion||candidate.finalVersion) for(let i=0;i<next.length;i++){const r=next[i]; if(r.id!==candidate.id&&r.engagementId===candidate.engagementId&&!r.isDeleted&&((candidate.currentVersion&&r.currentVersion)||(candidate.finalVersion&&r.finalVersion))) next[i]={...r,currentVersion:candidate.currentVersion?false:r.currentVersion,finalVersion:candidate.finalVersion?false:r.finalVersion,status:'Superseded',updatedAt:new Date().toISOString(),updatedByName:operatorName,recordVersion:r.recordVersion+1};}
  try{await this.repositories.managementLetters.replaceAll(next);}catch(error){await this.repositories.managementLetters.replaceAll(original);throw new AppError(`Atomic Management Letter version update failed. ${error instanceof Error?error.message:''}`,'ATOMIC_OPERATION_FAILED');} await this.activity.log({entityType:'Management Letter',entityId:candidate.id,action:existing?'Update':'Create',operatorName,newStatus:candidate.status,changedFieldSummary:existing?summarizeChanges(existing,candidate):`Management Letter ${candidate.reference} created`}); return candidate;
 }
 async saveRepresentationLetter(input:RepresentationLetterInput,operatorName:string,id?:string):Promise<RepresentationLetter>{
  await requireMutableEngagement(this.repositories.engagements,this.activity,input.engagementId,operatorName,'representation letter mutation'); const errors:string[]=[]; if(!input.reference.trim()||input.version<1) errors.push('Reference and positive Version are required.'); if(input.sentDate&&input.draftDate&&input.sentDate<input.draftDate) errors.push('Sent Date cannot precede Draft Date.'); if(input.signedDate&&input.sentDate&&input.signedDate<input.sentDate) errors.push('Signed Date cannot precede Sent Date.'); if(input.status==='Signed'&&(!input.signedDate||!input.signatory.trim())) errors.push('Signed status requires Signed Date and Signatory.'); const all=await this.representationLetters(input.engagementId); if(all.some(r=>!r.isDeleted&&r.version===input.version&&r.id!==id)) errors.push('Representation Letter version must be unique.'); if(errors.length) throw new ValidationError('Representation Letter could not be saved.',errors);
  const existing=id?await this.repositories.representationLetters.getById(id):null; const candidate:RepresentationLetter=existing?updateMetadata({...existing,...input},operatorName):{...input,...createMetadata(input.status,operatorName),status:input.status}; const original=await this.repositories.representationLetters.list({includeDeleted:true}); const next=original.map(r=>r.id===candidate.id?candidate:r); if(!existing)next.push(candidate); if(candidate.status==='Signed'&&candidate.currentVersion) for(let i=0;i<next.length;i++){const r=next[i];if(r.id!==candidate.id&&r.engagementId===candidate.engagementId&&!r.isDeleted&&r.status==='Signed'&&r.currentVersion) next[i]={...r,currentVersion:false,status:'Superseded',updatedAt:new Date().toISOString(),updatedByName:operatorName,recordVersion:r.recordVersion+1};}
  try{await this.repositories.representationLetters.replaceAll(next);}catch(error){await this.repositories.representationLetters.replaceAll(original);throw new AppError(`Atomic Representation Letter update failed. ${error instanceof Error?error.message:''}`,'ATOMIC_OPERATION_FAILED');} await this.activity.log({entityType:'Representation Letter',entityId:candidate.id,action:existing?'Update':'Create',operatorName,newStatus:candidate.status,changedFieldSummary:existing?summarizeChanges(existing,candidate):`Representation Letter ${candidate.reference} created`}); return candidate;
 }
 async issueReport(input:ReportIssueInput,operatorName:string,id?:string):Promise<FinalReportIssue>{
  await requireMutableEngagement(this.repositories.engagements,this.activity,input.engagementId,operatorName,'final report issue'); const errors:string[]=[]; const report=await this.repositories.reportVersions.getById(input.finalReportVersionId); if(!input.issueReference.trim()) errors.push('Issue Reference is required.'); if(!report||report.engagementId!==input.engagementId||report.status!=='Final Approved'||!report.finalVersion) errors.push('Only the selected Final Approved report version can be issued.'); if(!input.reportDate||!input.issueDate) errors.push('Report Date and Issue Date are required.'); if(input.reportDate&&input.issueDate&&input.issueDate<input.reportDate) errors.push('Issue Date cannot precede Report Date.'); if(!input.signedByPartnerId) errors.push('Signed By Partner is required.'); const partnerReview=(await this.repositories.partnerReviewRecords.list()).find(r=>r.engagementId===input.engagementId&&!r.isDeleted); if(!partnerReview||!['Approved','Completed'].includes(partnerReview.status)) errors.push('Partner Review approval is required before report issue.'); const reps=await this.representationLetters(input.engagementId); if(reps.some(r=>!r.isDeleted&&r.mandatory)&&!reps.some(r=>!r.isDeleted&&r.mandatory&&r.status==='Signed'&&r.currentVersion)) errors.push('Mandatory Representation Letter must be Signed.'); const notes=(await this.repositories.reviewNotes.list()).filter(n=>n.engagementId===input.engagementId&&['Critical','High'].includes(n.severity)&&!['Cleared','Cancelled'].includes(n.status)); if(notes.length) errors.push('Critical/High review notes must be cleared before issue.'); const checklist=(await this.repositories.auditCompletionItems.list()).filter(i=>i.engagementId===input.engagementId&&!i.isDeleted); if(!checklist.length||checklist.some(i=>i.required&&!['Completed','Reviewed','Not Applicable'].includes(i.status)||i.status==='Exception')) errors.push('Audit Completion Checklist must be complete without exceptions.'); const listedBlockers=await getListedGateBlockers(this.repositories,input.engagementId); if(listedBlockers.length) errors.push(...listedBlockers); const all=await this.issues(input.engagementId); if(all.some(r=>!r.isDeleted&&r.issueReference.toLowerCase()===input.issueReference.toLowerCase()&&r.id!==id)) errors.push('Issue Reference must be unique.'); if(errors.length) throw new ValidationError('Final report could not be issued.',errors);
  const existing=id?await this.repositories.reportIssues.getById(id):null; const record:FinalReportIssue=existing?updateMetadata({...existing,...input},operatorName):{...input,...createMetadata(input.status,operatorName),status:input.status}; const saved=existing?await this.repositories.reportIssues.update(record):await this.repositories.reportIssues.create(record); if(report&&input.status==='Issued'&&report.status!=='Issued') await this.repositories.reportVersions.update(updateMetadata({...report,status:'Issued'},operatorName)); await this.activity.log({entityType:'Final Report Issue',entityId:saved.id,action:'Issue',operatorName,newStatus:saved.status,changedFieldSummary:`Report issued under reference ${saved.issueReference}`}); return saved;
 }
}
