import type { IStorageGateway } from '../repositories/interfaces/IStorageGateway';
import { STORAGE_KEYS } from '../repositories/localStorage/keys';
import type { AppMeta, AppSettings, AuditEvent, BackupEnvelope, RestoreConflict, RestorePreview, RestoreResult } from '../types/models';
import { checksum } from '../utils/checksum';
import { AppError } from '../utils/errors';
import { createMetadata } from './helpers';
import { BACKUP_DATA_KEYS, validateMeta, validateModuleRecords, validateSettings } from '../utils/backupValidation';
import { DEFAULT_SETTINGS } from '../constants/statuses';

export type RestoreMode = 'merge' | 'replace';
type RawRecord = Record<string, unknown>;

const UNSAFE_OBJECT_KEYS = new Set(['__proto__', 'prototype', 'constructor']);
function findUnsafeObjectKey(value: unknown, path = 'backup'): string | null {
  if (!value || typeof value !== 'object') return null;
  if (Array.isArray(value)) {
    for (let index = 0; index < value.length; index += 1) {
      const found = findUnsafeObjectKey(value[index], `${path}[${index}]`);
      if (found) return found;
    }
    return null;
  }
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    if (UNSAFE_OBJECT_KEYS.has(key)) return `${path}.${key}`;
    const found = findUnsafeObjectKey(child, `${path}.${key}`);
    if (found) return found;
  }
  return null;
}

function checksumPayload(envelope: Omit<BackupEnvelope, 'checksum' | 'integritySummary' | 'moduleCounts'>): string {
  return JSON.stringify({ schemaVersion: envelope.schemaVersion, appVersion: envelope.appVersion, backupDate: envelope.backupDate, backupType: envelope.backupType, moduleKey: envelope.moduleKey ?? '', data: envelope.data, settings: envelope.settings, meta: envelope.meta });
}
function parseArray(raw: string | null, key: string): RawRecord[] {
  if (!raw) return [];
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) throw new AppError(`Current data for ${key} is corrupt.`, 'CORRUPT_DATA');
  return parsed as RawRecord[];
}

export class BackupService {
  constructor(private readonly storage: IStorageGateway, private readonly getSettings: () => AppSettings) {}

  private getMeta(settings: AppSettings): AppMeta {
    const raw = this.storage.getItem(STORAGE_KEYS.meta);
    if (raw) {
      try { const value: unknown = JSON.parse(raw); if (validateMeta(value).length === 0) return value as AppMeta; } catch { /* safe fallback */ }
    }
    return { schemaVersion: settings.schemaVersion, appVersion: settings.appVersion, initializedAt: new Date().toISOString(), lastBackupAt: '' };
  }
  private collectData(keys: readonly string[]): Record<string, unknown[]> { return Object.fromEntries(keys.map(key => [key, parseArray(this.storage.getItem(key), key)])); }

  createBackup(moduleKey?: string): BackupEnvelope {
    if (moduleKey && !BACKUP_DATA_KEYS.includes(moduleKey as (typeof BACKUP_DATA_KEYS)[number])) throw new AppError(`Unsupported module key: ${moduleKey}.`, 'INVALID_BACKUP_MODULE');
    const settings = this.getSettings(); const backupDate = new Date().toISOString(); const keys = moduleKey ? [moduleKey] : [...BACKUP_DATA_KEYS];
    const data = this.collectData(keys); const meta = { ...this.getMeta(settings), schemaVersion: settings.schemaVersion, appVersion: settings.appVersion, lastBackupAt: backupDate };
    const base = { schemaVersion: settings.schemaVersion, appVersion: settings.appVersion, backupDate, backupType: moduleKey ? 'module' as const : 'full' as const, moduleKey, data, settings, meta };
    const moduleCounts = Object.fromEntries(Object.entries(data).map(([key, records]) => [key, records.length]));
    const total = Object.values(moduleCounts).reduce((sum, count) => sum + count, 0);
    return { ...base, checksum: checksum(checksumPayload(base)), integritySummary: `${total} records across ${Object.keys(moduleCounts).length} module(s)`, moduleCounts };
  }

  parse(input: string): BackupEnvelope {
    try { const parsed: unknown = JSON.parse(input); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('Root must be an object'); return parsed as BackupEnvelope; }
    catch (error) { throw new AppError(`Invalid backup file. ${error instanceof Error ? error.message : ''}`.trim(), 'INVALID_BACKUP'); }
  }

  private effectiveRecords(backup: BackupEnvelope, mode: RestoreMode): Record<string, RawRecord[]> {
    const effective: Record<string, RawRecord[]> = {};
    for (const key of BACKUP_DATA_KEYS) {
      const current = parseArray(this.storage.getItem(key), key);
      const incoming = Array.isArray(backup.data?.[key]) ? backup.data[key] as RawRecord[] : undefined;
      if (!incoming) effective[key] = current;
      else if (mode === 'replace') effective[key] = structuredClone(incoming);
      else {
        const byId = new Map(current.map(record => [String(record.id), record]));
        for (const record of incoming) if (!byId.has(String(record.id))) byId.set(String(record.id), record);
        effective[key] = [...byId.values()];
      }
    }
    return effective;
  }

  private validateRelationships(backup: BackupEnvelope, mode: RestoreMode): string[] {
    const errors: string[] = []; const data = this.effectiveRecords(backup, mode);
    const map = (key: string) => new Map(data[key].map(record => [String(record.id), record]));
    const clients=map(STORAGE_KEYS.clients), contacts=map(STORAGE_KEYS.clientContacts), staff=map(STORAGE_KEYS.staff), engagements=map(STORAGE_KEYS.engagements);
    const team=map(STORAGE_KEYS.engagementTeam), tasks=map(STORAGE_KEYS.tasks), deadlines=map(STORAGE_KEYS.engagementDeadlines);
    const acceptance=map(STORAGE_KEYS.acceptanceReviews), independence=map(STORAGE_KEYS.independenceAssessments), letters=map(STORAGE_KEYS.engagementLetters), plans=map(STORAGE_KEYS.auditPlans), milestones=map(STORAGE_KEYS.planningMilestones);
    const risks=map(STORAGE_KEYS.auditRisks), materiality=map(STORAGE_KEYS.auditMateriality), templates=map(STORAGE_KEYS.programmeTemplates), programmes=map(STORAGE_KEYS.engagementProgrammes);
    const workingPapers=map(STORAGE_KEYS.workingPapers), evidence=map(STORAGE_KEYS.evidenceRegister), sampling=map(STORAGE_KEYS.samplingRegister), requests=map(STORAGE_KEYS.documentRequests), items=map(STORAGE_KEYS.documentRequestItems), reminders=map(STORAGE_KEYS.documentRequestReminders);
    const reviewNotes=map(STORAGE_KEYS.reviewNotes), completionItems=map(STORAGE_KEYS.auditCompletionItems), findings=map(STORAGE_KEYS.auditFindings), reportVersions=map(STORAGE_KEYS.reportVersions), managementLetters=map(STORAGE_KEYS.managementLetters), representationLetters=map(STORAGE_KEYS.representationLetters), reportIssues=map(STORAGE_KEYS.reportIssues), engagementLocks=map(STORAGE_KEYS.engagementLocks), amendments=map(STORAGE_KEYS.amendmentRequests), managerReviews=map(STORAGE_KEYS.managerReviewRecords), partnerReviews=map(STORAGE_KEYS.partnerReviewRecords);
    const listedCompliance=map(STORAGE_KEYS.listedComplianceItems), regulatoryDeadlines=map(STORAGE_KEYS.regulatoryDeadlines), committeeCommunications=map(STORAGE_KEYS.auditCommitteeCommunications), qualityReviews=map(STORAGE_KEYS.qualityReviews), keyAuditMatters=map(STORAGE_KEYS.keyAuditMatters);
    const taxAssignments=map(STORAGE_KEYS.taxAssignments), vatAssignments=map(STORAGE_KEYS.vatAssignments), rjscAssignments=map(STORAGE_KEYS.rjscAssignments), accountingAssignments=map(STORAGE_KEYS.accountingAssignments), advisoryAssignments=map(STORAGE_KEYS.advisoryAssignments);
    const timesheets=map(STORAGE_KEYS.timesheets), expenses=map(STORAGE_KEYS.expenses), invoices=map(STORAGE_KEYS.invoices), collections=map(STORAGE_KEYS.collections), communications=map(STORAGE_KEYS.communications), followUps=map(STORAGE_KEYS.followUps);
    const getEngagement = (id: unknown, label: string, recordId: unknown): RawRecord | undefined => { const engagement=engagements.get(String(id)); if(!engagement) errors.push(`${label} ${recordId} references missing engagement ${id}.`); return engagement; };
    const requireAudit = (record: RawRecord, label: string): RawRecord | undefined => { const engagement=getEngagement(record.engagementId,label,record.id); if(engagement&&engagement.serviceType!=='Audit') errors.push(`${label} ${record.id} must reference an Audit engagement.`); return engagement; };
    const staffReference = (id: unknown, label: string, recordId: unknown, role?: string, historical=false) => { if(!id) return; const member=staff.get(String(id)); if(!member) errors.push(`${label} ${recordId} references missing staff ${id}.`); else { if(role&&member.role!==role) errors.push(label === 'Engagement' ? `Engagement ${recordId} has invalid responsible ${role}; ${role} staff is required.` : `${label} ${recordId} has invalid ${role} reviewer/approver role; ${role} staff is required.`); if(!historical&&member.isActive!==true) errors.push(`${label} ${recordId} references inactive staff ${id}.`); } };
    const unique = (records: Iterable<RawRecord>, key: (r:RawRecord)=>string, label:string) => { const seen=new Set<string>(); for(const record of records){ if(record.isDeleted===true) continue; const value=key(record).toLowerCase(); if(!value) continue; if(seen.has(value)) errors.push(`Duplicate ${label}: ${value}.`); seen.add(value); } };

    for(const record of contacts.values()){ const client=clients.get(String(record.clientId)); if(!client) errors.push(`Contact ${record.id} references missing client ${record.clientId}.`); else if(record.isDeleted!==true&&record.isActive===true&&(client.isDeleted===true||['Inactive','Rejected'].includes(String(client.status)))) errors.push(`Active contact ${record.id} cannot belong to an archived/inactive client.`); }
    for(const record of engagements.values()){ if(!clients.has(String(record.clientId))) errors.push(`Engagement ${record.id} references missing client ${record.clientId}.`); const historical=record.isDeleted===true||['Locked','Closed','Cancelled'].includes(String(record.status)); staffReference(record.responsiblePartnerId,'Engagement',record.id,'Partner',historical); staffReference(record.responsibleManagerId,'Engagement',record.id,'Manager',historical); }
    for(const record of team.values()){ const engagement=getEngagement(record.engagementId,'Team assignment',record.id); const historical=record.isDeleted===true||record.isActive!==true||['Locked','Closed','Cancelled'].includes(String(engagement?.status)); staffReference(record.staffId,'Team assignment',record.id,record.assignmentRole==='Partner'?'Partner':record.assignmentRole==='Manager'?'Manager':undefined,historical); }
    unique(team.values(),r=>r.isActive===true?`${r.engagementId}|${r.staffId}`:'', 'active team assignment');
    for(const record of tasks.values()){ if(record.clientId&&!clients.has(String(record.clientId))) errors.push(`Task ${record.id} references missing client ${record.clientId}.`); const engagement=record.engagementId?getEngagement(record.engagementId,'Task',record.id):undefined; const historical=record.isDeleted===true||['Completed','Cancelled'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status)); staffReference(record.assigneeId,'Task',record.id,undefined,historical); staffReference(record.reviewerId,'Task',record.id,undefined,historical); }
    for(const record of deadlines.values()){ if(!clients.has(String(record.clientId))) errors.push(`Deadline ${record.id} references missing client ${record.clientId}.`); const engagement=getEngagement(record.engagementId,'Deadline',record.id); const historical=record.isDeleted===true||['Completed','Cancelled'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status)); staffReference(record.ownerId,'Deadline',record.id,undefined,historical); }

    const onePerEngagement = (records: Iterable<RawRecord>, label:string) => unique(records,r=>String(r.engagementId),label);
    onePerEngagement(acceptance.values(),'Acceptance record for engagement'); onePerEngagement(independence.values(),'Independence record for engagement'); onePerEngagement(plans.values(),'Planning Memo for engagement');
    for(const record of acceptance.values()){ const engagement=requireAudit(record,'Acceptance Review'); const historical=record.isDeleted===true||['Locked','Rejected'].includes(String(record.status)); staffReference(record.managerReviewerId,'Acceptance Review',record.id,'Manager',historical); staffReference(record.partnerApproverId,'Acceptance Review',record.id,'Partner',historical); if(engagement&&record.managerReviewerId&&record.managerReviewerId!==engagement.responsibleManagerId) errors.push(`Acceptance Review ${record.id} Manager reviewer is not the Responsible Manager.`); if(engagement&&record.partnerApproverId&&record.partnerApproverId!==engagement.responsiblePartnerId) errors.push(`Acceptance Review ${record.id} Partner approver is not the Responsible Partner.`); }
    for(const record of independence.values()){ requireAudit(record,'Independence Assessment'); staffReference(record.assessedById,'Independence Assessment',record.id,undefined,record.isDeleted===true||['Cleared','Rejected','Locked'].includes(String(record.status))); }
    for(const record of letters.values()) requireAudit(record,'Engagement Letter');
    unique(letters.values(),r=>`${r.engagementId}|${r.letterReference}`,'Engagement Letter reference');
    for(const engagement of engagements.values()){ const accepted=[...letters.values()].filter(r=>r.isDeleted!==true&&r.engagementId===engagement.id&&r.status==='Accepted'); if(accepted.length>1) errors.push(`Engagement ${engagement.id} has multiple current Accepted letters.`); }
    for(const record of plans.values()){ const engagement=requireAudit(record,'Audit Planning Memo'); const historical=record.isDeleted===true||['Approved','Locked'].includes(String(record.status)); staffReference(record.managerReviewerId,'Audit Planning Memo',record.id,'Manager',historical); staffReference(record.partnerApproverId,'Audit Planning Memo',record.id,'Partner',historical); if(engagement&&record.managerReviewerId&&record.managerReviewerId!==engagement.responsibleManagerId) errors.push(`Audit Planning Memo ${record.id} Manager reviewer is not the Responsible Manager.`); if(engagement&&record.partnerApproverId&&record.partnerApproverId!==engagement.responsiblePartnerId) errors.push(`Audit Planning Memo ${record.id} Partner approver is not the Responsible Partner.`); }
    for(const record of milestones.values()){ const engagement=requireAudit(record,'Planning Milestone'); if(record.ownerId && !staff.has(String(record.ownerId))) errors.push(`Planning Milestone ${record.id} has missing owner ${record.ownerId}.`); else staffReference(record.ownerId,'Planning Milestone',record.id,undefined,record.isDeleted===true||['Completed','Cancelled'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status))); }
    unique(milestones.values(),r=>`${r.engagementId}|${r.milestoneType}`,'Planning milestone');

    for(const record of risks.values()){ const engagement=requireAudit(record,'Audit Risk'); const acceptanceRecord=[...acceptance.values()].find(item=>item.engagementId===record.engagementId&&item.isDeleted!==true); const independenceRecord=[...independence.values()].find(item=>item.engagementId===record.engagementId&&item.isDeleted!==true); if(acceptanceRecord?.status!=='Approved') errors.push(`Audit Risk ${record.id} requires Approved Acceptance.`); if(independenceRecord?.status!=='Cleared') errors.push(`Audit Risk ${record.id} requires Cleared Independence.`); const historical=record.isDeleted===true||['Approved','Closed','Rejected'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status)); staffReference(record.assignedStaffId,'Audit Risk',record.id,undefined,historical); staffReference(record.preparedById,'Audit Risk',record.id,undefined,historical); staffReference(record.managerReviewerId,'Audit Risk',record.id,'Manager',historical); staffReference(record.partnerReviewerId,'Audit Risk',record.id,'Partner',historical); }
    unique(risks.values(),r=>`${r.engagementId}|${r.riskCode}`,'Audit Risk code');
    for(const record of materiality.values()){ const engagement=requireAudit(record,'Audit Materiality'); const historical=record.isDeleted===true||['Approved','Superseded','Locked'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status)); staffReference(record.preparedById,'Audit Materiality',record.id,undefined,historical); staffReference(record.managerReviewerId,'Audit Materiality',record.id,'Manager',historical); staffReference(record.partnerApproverId,'Audit Materiality',record.id,'Partner',historical); }
    unique(materiality.values(),r=>`${r.engagementId}|${r.version}`,'Materiality version');
    for(const engagement of engagements.values()){ if([...materiality.values()].filter(r=>r.isDeleted!==true&&r.engagementId===engagement.id&&r.status==='Approved').length>1) errors.push(`Engagement ${engagement.id} has multiple current Approved materiality versions.`); }
    for(const record of templates.values()){ if(record.applicableIndustryId&&!map(STORAGE_KEYS.industries).has(String(record.applicableIndustryId))) errors.push(`Programme Template ${record.id} references missing industry ${record.applicableIndustryId}.`); }
    unique(templates.values(),r=>`${r.templateCode}|${r.version}`,'Programme Template version'); unique(templates.values(),r=>`${r.procedureCode}|${r.version}`,'Programme Template procedure version');
    for(const record of programmes.values()){ const engagement=requireAudit(record,'Audit Programme'); if(record.templateId&&!templates.has(String(record.templateId))) errors.push(`Audit Programme ${record.id} references missing template ${record.templateId}.`); staffReference(record.assigneeId,'Audit Programme',record.id,undefined,record.isDeleted===true||['Completed','Not Applicable','Reviewed'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status))); staffReference(record.reviewerId,'Audit Programme',record.id,undefined,record.isDeleted===true||record.status==='Reviewed'||['Locked','Closed','Cancelled'].includes(String(engagement?.status))); for(const riskId of (record.linkedRiskIds as unknown[]??[])){ const risk=risks.get(String(riskId)); if(!risk||risk.engagementId!==record.engagementId) errors.push(`Audit Programme ${record.id} references invalid risk ${riskId}.`); } }
    unique(programmes.values(),r=>`${r.engagementId}|${r.procedureCode}`,'Engagement programme procedure code');
    for(const record of workingPapers.values()){ const engagement=requireAudit(record,'Working Paper'); if(record.linkedProgrammeProcedureId){ const procedure=programmes.get(String(record.linkedProgrammeProcedureId)); if(!procedure||procedure.engagementId!==record.engagementId) errors.push(`Working Paper ${record.id} references invalid programme procedure ${record.linkedProgrammeProcedureId}.`); } for(const riskId of (record.linkedRiskIds as unknown[]??[])){ const risk=risks.get(String(riskId)); if(!risk||risk.engagementId!==record.engagementId) errors.push(`Working Paper ${record.id} references invalid risk ${riskId}.`); } staffReference(record.preparedById,'Working Paper',record.id,undefined,record.isDeleted===true||['Final','Locked'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status))); staffReference(record.reviewerId,'Working Paper',record.id,undefined,record.isDeleted===true||['Final','Locked'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status))); }
    unique(workingPapers.values(),r=>`${r.engagementId}|${r.wpReference}`,'Working Paper reference');
    for(const record of evidence.values()){ requireAudit(record,'Evidence'); if(record.workingPaperId){ const wp=workingPapers.get(String(record.workingPaperId)); if(!wp||wp.engagementId!==record.engagementId) errors.push(`Evidence ${record.id} references invalid Working Paper ${record.workingPaperId}.`); } staffReference(record.acceptedById,'Evidence',record.id,undefined,record.isDeleted===true||['Accepted','Rejected','Superseded'].includes(String(record.status))); }
    unique(evidence.values(),r=>`${r.engagementId}|${r.evidenceReference}`,'Evidence reference');
    for(const record of sampling.values()){ requireAudit(record,'Sampling'); const wp=workingPapers.get(String(record.workingPaperId)); if(!wp||wp.engagementId!==record.engagementId) errors.push(`Sampling ${record.id} references invalid Working Paper ${record.workingPaperId}.`); staffReference(record.preparedById,'Sampling',record.id,undefined,record.isDeleted===true||record.status==='Reviewed'); staffReference(record.reviewerId,'Sampling',record.id,undefined,record.isDeleted===true||record.status==='Reviewed'); }
    for(const record of requests.values()){ const engagement=requireAudit(record,'Document Request'); const contact=record.clientContactId?contacts.get(String(record.clientContactId)):undefined; if(record.clientContactId&&(!contact||contact.clientId!==engagement?.clientId)) errors.push(`Document Request ${record.id} references invalid client contact ${record.clientContactId}.`); staffReference(record.responsibleStaffId,'Document Request',record.id,undefined,record.isDeleted===true||['Accepted','Waived','Closed'].includes(String(record.status))||['Locked','Closed','Cancelled'].includes(String(engagement?.status))); const requestItems=[...items.values()].filter(item=>item.requestId===record.id&&item.isDeleted!==true); if(record.status==='Sent'&&requestItems.length===0) errors.push(`Sent Document Request ${record.id} requires at least one item.`); if(record.status==='Closed'&&requestItems.some(item=>!['Accepted','Waived'].includes(String(item.status)))) errors.push(`Closed Document Request ${record.id} contains unresolved items.`); }
    unique(requests.values(),r=>`${r.engagementId}|${r.requestReference}`,'Document Request reference');
    for(const record of items.values()){ const request=requests.get(String(record.requestId)); if(!request) errors.push(`Document Request Item ${record.id} references missing request ${record.requestId}.`); const engagement=request?engagements.get(String(request.engagementId)):undefined; if(record.assignedClientContactId){ const contact=contacts.get(String(record.assignedClientContactId)); if(!contact||contact.clientId!==engagement?.clientId) errors.push(`Document Request Item ${record.id} references invalid client contact ${record.assignedClientContactId}.`); } if(record.linkedWorkingPaperId){ const wp=workingPapers.get(String(record.linkedWorkingPaperId)); if(!wp||wp.engagementId!==request?.engagementId) errors.push(`Document Request Item ${record.id} references invalid Working Paper ${record.linkedWorkingPaperId}.`); } }
    unique(items.values(),r=>`${r.requestId}|${r.itemCode}`,'Document Request Item code');
    for(const record of reminders.values()){ if(!requests.has(String(record.requestId))) errors.push(`Document Request Reminder ${record.id} references missing request ${record.requestId}.`); if(record.requestItemId){ const item=items.get(String(record.requestItemId)); if(!item||item.requestId!==record.requestId) errors.push(`Document Request Reminder ${record.id} references invalid item ${record.requestItemId}.`); } }


    const relatedMaps: Record<string,Map<string,RawRecord>> = { Engagement:engagements,'Audit Programme Procedure':programmes,'Working Paper':workingPapers,Evidence:evidence,Risk:risks,Materiality:materiality,'Document Request':requests,'Audit Report Version':reportVersions };
    for(const record of reviewNotes.values()){ requireAudit(record,'Review Note'); const related=relatedMaps[String(record.relatedRecordType)]; if(!related||!related.has(String(record.relatedRecordId))) errors.push(`Review Note ${record.id} references invalid ${record.relatedRecordType} ${record.relatedRecordId}.`); staffReference(record.raisedById,'Review Note',record.id,undefined,true); staffReference(record.assignedToId,'Review Note',record.id,undefined,true); staffReference(record.responseById,'Review Note',record.id,undefined,true); staffReference(record.clearedById,'Review Note',record.id,undefined,true); }
    unique(reviewNotes.values(),r=>`${r.engagementId}|${r.reviewNoteReference}`,'Review Note reference');
    for(const record of completionItems.values()){ requireAudit(record,'Audit Completion Item'); staffReference(record.responsiblePersonId,'Audit Completion Item',record.id,undefined,true); staffReference(record.completedById,'Audit Completion Item',record.id,undefined,true); staffReference(record.reviewerId,'Audit Completion Item',record.id,undefined,true); }
    unique(completionItems.values(),r=>`${r.engagementId}|${r.checklistCode}`,'Completion Checklist code');
    for(const record of findings.values()){ requireAudit(record,'Audit Finding'); if(record.linkedRiskId){const risk=risks.get(String(record.linkedRiskId));if(!risk||risk.engagementId!==record.engagementId)errors.push(`Audit Finding ${record.id} references invalid Risk ${record.linkedRiskId}.`);} if(record.linkedWorkingPaperId){const wp=workingPapers.get(String(record.linkedWorkingPaperId));if(!wp||wp.engagementId!==record.engagementId)errors.push(`Audit Finding ${record.id} references invalid Working Paper ${record.linkedWorkingPaperId}.`);} }
    unique(findings.values(),r=>`${r.engagementId}|${r.findingReference}`,'Audit Finding reference');
    for(const record of reportVersions.values()){ requireAudit(record,'Audit Report Version'); staffReference(record.managerReviewerId,'Audit Report Version',record.id,'Manager',true); staffReference(record.partnerApproverId,'Audit Report Version',record.id,'Partner',true); }
    unique(reportVersions.values(),r=>`${r.engagementId}|${r.reportType}|${r.versionNumber}`,'Audit Report version');
    for(const engagement of engagements.values()){ const reports=[...reportVersions.values()].filter(r=>r.engagementId===engagement.id&&r.isDeleted!==true); if(reports.filter(r=>r.currentVersion===true).length>1)errors.push(`Engagement ${engagement.id} has multiple current Audit Report versions.`); if(reports.filter(r=>r.finalVersion===true&&['Final Approved','Issued'].includes(String(r.status))).length>1)errors.push(`Engagement ${engagement.id} has multiple final Audit Report versions.`); }
    for(const record of managementLetters.values()){ requireAudit(record,'Management Letter'); for(const findingId of (record.findingIds as unknown[]??[])){const finding=findings.get(String(findingId));if(!finding||finding.engagementId!==record.engagementId||finding.reportable!==true)errors.push(`Management Letter ${record.id} references invalid/non-reportable Finding ${findingId}.`);} staffReference(record.managerReviewerId,'Management Letter',record.id,'Manager',true);staffReference(record.partnerApproverId,'Management Letter',record.id,'Partner',true); }
    unique(managementLetters.values(),r=>`${r.engagementId}|${r.version}`,'Management Letter version');
    for(const record of representationLetters.values()) requireAudit(record,'Representation Letter'); unique(representationLetters.values(),r=>`${r.engagementId}|${r.version}`,'Representation Letter version');
    for(const engagement of engagements.values()){if([...representationLetters.values()].filter(r=>r.engagementId===engagement.id&&r.isDeleted!==true&&r.status==='Signed'&&r.currentVersion===true).length>1)errors.push(`Engagement ${engagement.id} has multiple current Signed Representation Letters.`);}
    for(const record of reportIssues.values()){ requireAudit(record,'Final Report Issue'); const report=reportVersions.get(String(record.finalReportVersionId)); if(!report||report.engagementId!==record.engagementId||!['Final Approved','Issued'].includes(String(report.status)))errors.push(`Final Report Issue ${record.id} references invalid Final Report Version ${record.finalReportVersionId}.`); staffReference(record.signedByPartnerId,'Final Report Issue',record.id,'Partner',true); }
    unique(reportIssues.values(),r=>`${r.engagementId}|${r.issueReference}`,'Final Report Issue reference');
    for(const record of engagementLocks.values()){ const engagement=requireAudit(record,'Engagement File Lock'); staffReference(record.lockedById,'Engagement File Lock',record.id,undefined,true); if(engagement&&!['Locked','Closed'].includes(String(engagement.status)))errors.push(`Engagement File Lock ${record.id} references engagement that is not Locked/Closed.`); }
    for(const record of amendments.values()){ const engagement=requireAudit(record,'Amendment'); staffReference(record.requestedById,'Amendment',record.id,undefined,true); if(engagement&&!['Locked','Closed'].includes(String(engagement.status)))errors.push(`Amendment ${record.id} requires a Locked/Closed engagement.`); }
    unique(amendments.values(),r=>`${r.engagementId}|${r.amendmentReference}`,'Amendment reference');
    for(const record of managerReviews.values()){ requireAudit(record,'Manager Review'); staffReference(record.managerId,'Manager Review',record.id,'Manager',true); }
    onePerEngagement(managerReviews.values(),'Manager Review record for engagement');
    for(const record of partnerReviews.values()){ requireAudit(record,'Partner Review'); staffReference(record.partnerId,'Partner Review',record.id,'Partner',true); if(record.selectedReportVersionId&&!reportVersions.has(String(record.selectedReportVersionId)))errors.push(`Partner Review ${record.id} references missing Report Version ${record.selectedReportVersionId}.`); }
    onePerEngagement(partnerReviews.values(),'Partner Review record for engagement');

    const requireListedAudit=(record:RawRecord,label:string)=>{const engagement=requireAudit(record,label);const client=engagement?clients.get(String(engagement.clientId)):undefined;if(engagement&&engagement.listedPieWorkflowRequired!==true&&client?.isListedPie!==true)errors.push(`${label} ${record.id} requires a Listed/PIE client or engagement.`);return engagement;};
    for(const record of listedCompliance.values()){requireListedAudit(record,'Listed Compliance Item');staffReference(record.ownerId,'Listed Compliance Item',record.id,undefined,true);staffReference(record.completedById,'Listed Compliance Item',record.id,undefined,true);staffReference(record.reviewerId,'Listed Compliance Item',record.id,undefined,true);} unique(listedCompliance.values(),r=>`${r.engagementId}|${r.checklistCode}`,'Listed checklist code');
    for(const record of regulatoryDeadlines.values()){const engagement=requireListedAudit(record,'Regulatory Deadline');if(!clients.has(String(record.clientId)))errors.push(`Regulatory Deadline ${record.id} references missing Client ${record.clientId}.`);else if(engagement&&record.clientId!==engagement.clientId)errors.push(`Regulatory Deadline ${record.id} client does not match engagement client.`);staffReference(record.responsiblePersonId,'Regulatory Deadline',record.id,undefined,true);}
    for(const record of committeeCommunications.values()){requireListedAudit(record,'Audit Committee Communication');staffReference(record.responsiblePersonId,'Audit Committee Communication',record.id,undefined,true);} unique(committeeCommunications.values(),r=>`${r.engagementId}|${r.communicationReference}`,'Audit Committee communication reference');
    for(const record of qualityReviews.values()){const engagement=requireListedAudit(record,'Engagement Quality Review');staffReference(record.qualityReviewerId,'Engagement Quality Review',record.id,'Quality Reviewer',record.status==='Not Required');if(engagement&&[engagement.responsiblePartnerId,engagement.responsibleManagerId].includes(record.qualityReviewerId))errors.push(`Engagement Quality Review ${record.id} reviewer lacks independence.`);} onePerEngagement(qualityReviews.values(),'Engagement Quality Review record for engagement');
    for(const record of keyAuditMatters.values()){requireListedAudit(record,'Key Audit Matter');if(record.relatedSignificantRiskId){const risk=risks.get(String(record.relatedSignificantRiskId));if(!risk||risk.engagementId!==record.engagementId||!(risk.significantRisk===true||risk.fraudRisk===true))errors.push(`Key Audit Matter ${record.id} references invalid Significant/Fraud Risk ${record.relatedSignificantRiskId}.`);}for(const wid of (record.relatedWorkingPaperIds as unknown[]??[])){const wp=workingPapers.get(String(wid));if(!wp||wp.engagementId!==record.engagementId)errors.push(`Key Audit Matter ${record.id} references invalid Working Paper ${wid}.`);}staffReference(record.managerReviewerId,'Key Audit Matter',record.id,'Manager',true);staffReference(record.partnerApproverId,'Key Audit Matter',record.id,'Partner',true);staffReference(record.qualityReviewerId,'Key Audit Matter',record.id,'Quality Reviewer',true);} unique(keyAuditMatters.values(),r=>`${r.engagementId}|${r.kamReference}`,'KAM reference');
    const requireService=(record:RawRecord,label:string,service:string)=>{const engagement=getEngagement(record.engagementId,label,record.id);if(engagement&&engagement.serviceType!==service)errors.push(`${label} ${record.id} must reference a ${service} engagement.`);return engagement;};
    for(const record of taxAssignments.values()){requireService(record,'Tax Assignment','Tax');staffReference(record.responsibleStaffId,'Tax Assignment',record.id,undefined,true);staffReference(record.managerReviewerId,'Tax Assignment',record.id,'Manager',true);} onePerEngagement(taxAssignments.values(),'Tax Assignment record for engagement');
    for(const record of vatAssignments.values()){requireService(record,'VAT Assignment','VAT');staffReference(record.responsibleStaffId,'VAT Assignment',record.id,undefined,true);staffReference(record.managerReviewerId,'VAT Assignment',record.id,'Manager',true);} onePerEngagement(vatAssignments.values(),'VAT Assignment record for engagement');
    for(const record of rjscAssignments.values()){requireService(record,'RJSC Assignment','RJSC');staffReference(record.responsibleStaffId,'RJSC Assignment',record.id,undefined,true);staffReference(record.reviewerId,'RJSC Assignment',record.id,undefined,true);} onePerEngagement(rjscAssignments.values(),'RJSC Assignment record for engagement');
    for(const record of accountingAssignments.values()){requireService(record,'Accounting Assignment','Accounting');staffReference(record.responsibleStaffId,'Accounting Assignment',record.id,undefined,true);staffReference(record.reviewerId,'Accounting Assignment',record.id,undefined,true);} onePerEngagement(accountingAssignments.values(),'Accounting Assignment record for engagement');
    for(const record of advisoryAssignments.values()){requireService(record,'Advisory Assignment','Advisory');staffReference(record.responsiblePartnerId,'Advisory Assignment',record.id,'Partner',true);staffReference(record.responsibleManagerId,'Advisory Assignment',record.id,'Manager',true);} onePerEngagement(advisoryAssignments.values(),'Advisory Assignment record for engagement');


    for(const record of timesheets.values()){staffReference(record.staffId,'Timesheet',record.id,undefined,true);if(record.reviewerId)staffReference(record.reviewerId,'Timesheet',record.id,undefined,true);if(record.engagementId)getEngagement(record.engagementId,'Timesheet',record.id);}
    for(const record of expenses.values()){if(record.engagementId)getEngagement(record.engagementId,'Expense',record.id);staffReference(record.claimedById,'Expense',record.id,undefined,true);if(record.reviewerId)staffReference(record.reviewerId,'Expense',record.id,undefined,true);}
    unique(invoices.values(),r=>String(r.invoiceNumber),'invoice number');for(const record of invoices.values()){const engagement=getEngagement(record.engagementId,'Invoice',record.id);if(!clients.has(String(record.clientId)))errors.push(`Invoice ${record.id} references missing client ${record.clientId}.`);if(engagement&&String(engagement.clientId)!==String(record.clientId))errors.push(`Invoice ${record.id} client does not match its engagement.`);if(record.preparedById)staffReference(record.preparedById,'Invoice',record.id,undefined,true);if(record.reviewerId)staffReference(record.reviewerId,'Invoice',record.id,undefined,true);}
    unique(collections.values(),r=>String(r.collectionReference),'collection reference');for(const record of collections.values()){const invoice=invoices.get(String(record.invoiceId));if(!invoice)errors.push(`Collection ${record.id} references missing invoice ${record.invoiceId}.`);else if(String(invoice.clientId)!==String(record.clientId)||String(invoice.engagementId)!==String(record.engagementId))errors.push(`Collection ${record.id} client/engagement does not match its invoice.`);if(record.recordedById)staffReference(record.recordedById,'Collection',record.id,undefined,true);}
    for(const record of communications.values()){if(!clients.has(String(record.clientId)))errors.push(`Communication ${record.id} references missing client ${record.clientId}.`);if(record.engagementId){const engagement=getEngagement(record.engagementId,'Communication',record.id);if(engagement&&String(engagement.clientId)!==String(record.clientId))errors.push(`Communication ${record.id} client does not match its engagement.`);}if(record.followUpOwnerId)staffReference(record.followUpOwnerId,'Communication',record.id,undefined,true);}
    unique(followUps.values(),r=>String(r.followUpReference),'follow-up reference');for(const record of followUps.values()){if(!clients.has(String(record.clientId)))errors.push(`Follow-up ${record.id} references missing client ${record.clientId}.`);if(record.engagementId){const engagement=getEngagement(record.engagementId,'Follow-up',record.id);if(engagement&&String(engagement.clientId)!==String(record.clientId))errors.push(`Follow-up ${record.id} client does not match its engagement.`);}staffReference(record.ownerId,'Follow-up',record.id,undefined,true);if(record.sourceType==='Communication'&&record.sourceId&&!communications.has(String(record.sourceId)))errors.push(`Follow-up ${record.id} references missing Communication ${record.sourceId}.`);}

    const entityMaps: Record<string,Map<string,RawRecord>> = { Client:clients,'Client Contact':contacts,Staff:staff,Engagement:engagements,'Engagement Team':team,Task:tasks,Deadline:deadlines,'Acceptance Review':acceptance,'Independence Assessment':independence,'Engagement Letter':letters,'Audit Planning Memo':plans,'Planning Milestone':milestones,'Audit Risk':risks,'Audit Materiality':materiality,'Programme Template':templates,'Audit Programme':programmes,'Working Paper':workingPapers,Evidence:evidence,Sampling:sampling,'Document Request':requests,'Document Request Item':items,'Review Note':reviewNotes,'Audit Completion Item':completionItems,'Audit Finding':findings,'Audit Report Version':reportVersions,'Management Letter':managementLetters,'Representation Letter':representationLetters,'Final Report Issue':reportIssues,'Engagement File Lock':engagementLocks,Amendment:amendments,'Manager Review':managerReviews,'Partner Review':partnerReviews,'Listed Compliance Item':listedCompliance,'Regulatory Deadline':regulatoryDeadlines,'Audit Committee Communication':committeeCommunications,'Engagement Quality Review':qualityReviews,'Key Audit Matter':keyAuditMatters,'Tax Assignment':taxAssignments,'VAT Assignment':vatAssignments,'RJSC Assignment':rjscAssignments,'Accounting Assignment':accountingAssignments,'Advisory Assignment':advisoryAssignments,Timesheet:timesheets,Expense:expenses,Invoice:invoices,Collection:collections,Communication:communications,'Follow-up':followUps };
    for(const event of data[STORAGE_KEYS.auditEvents]){ const entityMap=entityMaps[String(event.entityType)]; if(entityMap&&!entityMap.has(String(event.entityId))) errors.push(`Activity event ${event.id} references missing ${event.entityType} ${event.entityId}.`); }
    return [...new Set(errors)];
  }

  preview(backup: BackupEnvelope, mode: RestoreMode = 'merge'): RestorePreview {
    const errors:string[]=[]; const warnings:string[]=[]; const conflicts:RestoreConflict[]=[];
    if(!backup||typeof backup!=='object') errors.push('Backup root is invalid.');
    if(backup.schemaVersion==='1.0') errors.push('Phase 1 backup schema 1.0 cannot be imported directly into Complete Phase 6. Upgrade it sequentially through the earlier completed application phases first. No existing data has been changed.');
    else if(backup.schemaVersion==='2.0') errors.push('Phase 2A backup schema 2.0 cannot be imported directly into Complete Phase 6. Upgrade sequentially through the earlier completed phases first. No existing data has been changed.');
    else if(backup.schemaVersion==='3.0') errors.push('Complete Phase 2 backup schema 3.0 cannot be imported directly into Complete Phase 6. Upgrade sequentially through Phase 3, 4 and 5 first. No existing data has been changed.');
    else if(backup.schemaVersion==='4.0') errors.push('Complete Phase 3 backup schema 4.0 cannot be imported directly into Complete Phase 6. Upgrade sequentially through Phase 4 and Phase 5 first. No existing data has been changed.');
    else if(backup.schemaVersion==='5.0') errors.push('Complete Phase 4 backup schema 5.0 cannot be imported directly into Complete Phase 6. Open Phase 5 against the existing browser data and export a schema 6.0 backup first. No existing data has been changed.');
    else if(backup.schemaVersion==='6.0') errors.push('Complete Phase 5 backup schema 6.0 cannot be imported directly into Complete Phase 6. Open this Phase 6 application against the existing Phase 5 browser data and export a schema 7.0 backup. No existing data has been changed.');
    else if(backup.schemaVersion!==DEFAULT_SETTINGS.schemaVersion) errors.push(`Unsupported schema version ${String(backup.schemaVersion)}. Expected ${DEFAULT_SETTINGS.schemaVersion}.`);
    if(backup.backupType!=='full'&&backup.backupType!=='module') errors.push('backupType must be full or module.');
    if(!backup.data||typeof backup.data!=='object'||Array.isArray(backup.data)) errors.push('Backup data must be an object.');
    const unsafePath=findUnsafeObjectKey(backup); if(unsafePath) errors.push(`Backup contains a prohibited object key at ${unsafePath}.`);
    errors.push(...validateSettings(backup.settings),...validateMeta(backup.meta));
    if(backup.settings?.schemaVersion!==backup.schemaVersion||backup.meta?.schemaVersion!==backup.schemaVersion) errors.push('Backup envelope, settings and meta schema versions must match.');
    if(backup.settings?.appVersion!==backup.appVersion||backup.meta?.appVersion!==backup.appVersion) errors.push('Backup envelope, settings and meta app versions must match.');
    const dataKeys=backup.data&&typeof backup.data==='object'?Object.keys(backup.data):[];
    for(const key of dataKeys) errors.push(...validateModuleRecords(key,backup.data[key]));
    if(backup.backupType==='full'){ const missing=BACKUP_DATA_KEYS.filter(key=>!dataKeys.includes(key)); if(missing.length) errors.push(`Full backup is missing required modules for Complete Phase 6: ${missing.join(', ')}.`); const total=dataKeys.reduce((sum,key)=>sum+(Array.isArray(backup.data[key])?backup.data[key].length:0),0); if(total===0) errors.push('Empty full backups cannot be imported.'); }
    if(backup.backupType==='module'){ if(!backup.moduleKey||!BACKUP_DATA_KEYS.includes(backup.moduleKey as (typeof BACKUP_DATA_KEYS)[number])) errors.push('Per-module backup has an invalid moduleKey.'); if(dataKeys.length!==1||dataKeys[0]!==backup.moduleKey) errors.push('Per-module backup must contain exactly its declared module.'); }
    if(!backup.moduleCounts||typeof backup.moduleCounts!=='object'||Array.isArray(backup.moduleCounts)) errors.push('moduleCounts must be an object.'); else { for(const key of dataKeys){const actual=Array.isArray(backup.data[key])?backup.data[key].length:0;if(backup.moduleCounts[key]!==actual)errors.push(`moduleCounts.${key} does not match the backup payload.`);} }
    const actualTotal=dataKeys.reduce((sum,key)=>sum+(Array.isArray(backup.data[key])?backup.data[key].length:0),0); const expectedIntegrity=`${actualTotal} records across ${dataKeys.length} module(s)`; if(backup.integritySummary!==expectedIntegrity) errors.push('Backup integrity summary does not match its module payload.');
    if(!errors.length) errors.push(...this.validateRelationships(backup,mode));
    for(const [module,records] of Object.entries(backup.data??{})){ if(!Array.isArray(records)) continue; const currentIds=new Set(parseArray(this.storage.getItem(module),module).map(record=>String(record.id))); for(const record of records as RawRecord[]) if(currentIds.has(String(record.id))) conflicts.push({module,recordId:String(record.id),reason:mode==='merge'?'Existing record preserved in merge mode':'Existing record will be replaced'}); }
    const expectedChecksum=checksum(checksumPayload({schemaVersion:backup.schemaVersion,appVersion:backup.appVersion,backupDate:backup.backupDate,backupType:backup.backupType,moduleKey:backup.moduleKey,data:backup.data,settings:backup.settings,meta:backup.meta}));
    const checksumMatches=expectedChecksum===backup.checksum; if(!checksumMatches) errors.push('Backup checksum does not match its complete payload.'); if(conflicts.length) warnings.push(`${conflicts.length} existing record conflict(s) detected.`);
    return {valid:errors.length===0,errors,warnings,moduleCounts:backup.moduleCounts??Object.fromEntries(dataKeys.map(key=>[key,Array.isArray(backup.data[key])?backup.data[key].length:0])),conflicts,checksumMatches};
  }

  async restore(backup: BackupEnvelope, mode: RestoreMode, operatorName: string): Promise<RestoreResult> {
    const preview=this.preview(backup,mode); if(!preview.valid) throw new AppError('Backup cannot be restored.','INVALID_BACKUP',preview.errors);
    const targetKeys=new Set<string>(Object.keys(backup.data)); if(backup.backupType==='full'){targetKeys.add(STORAGE_KEYS.settings);targetKeys.add(STORAGE_KEYS.meta);} targetKeys.add(STORAGE_KEYS.auditEvents);
    // Capture the exact pre-call state before createBackup() can initialise missing settings/meta.
    const originals=new Map([...targetKeys].map(key=>[key,this.storage.getItem(key)]));
    const preImport=this.createBackup(); const preImportBackupKey=`afm:pre_import_backup:${Date.now()}`; const preImportJson=JSON.stringify(preImport);
    this.storage.setItem(preImportBackupKey,preImportJson); if(this.storage.getItem(preImportBackupKey)!==preImportJson) throw new AppError('Pre-import backup verification failed.','PREIMPORT_BACKUP_FAILED');
    const staged=new Map<string,string>(); let successCount=0; const conflicts:RestoreConflict[]=[];
    for(const [module,incomingRaw] of Object.entries(backup.data)){ const incoming=incomingRaw as RawRecord[]; if(mode==='replace'){staged.set(module,JSON.stringify(incoming));successCount+=incoming.length;} else {const current=parseArray(this.storage.getItem(module),module);const byId=new Map(current.map(record=>[String(record.id),record]));for(const record of incoming){const id=String(record.id);if(byId.has(id)) conflicts.push({module,recordId:id,reason:'Existing record preserved in merge mode'});else{byId.set(id,record);successCount++;}}staged.set(module,JSON.stringify([...byId.values()]));} }
    if(backup.backupType==='full'){staged.set(STORAGE_KEYS.settings,JSON.stringify(backup.settings));staged.set(STORAGE_KEYS.meta,JSON.stringify(backup.meta));successCount+=2;}
    const currentAudit=staged.has(STORAGE_KEYS.auditEvents)?parseArray(staged.get(STORAGE_KEYS.auditEvents)??null,STORAGE_KEYS.auditEvents):parseArray(this.storage.getItem(STORAGE_KEYS.auditEvents),STORAGE_KEYS.auditEvents);
    const auditEvent:AuditEvent={...createMetadata('Recorded',operatorName),entityType:'Backup',entityId:backup.backupDate,action:'Backup Import',previousStatus:'',newStatus:'',changedFieldSummary:`${mode} restore committed: ${successCount} item(s), ${conflicts.length} conflict(s)`,operatorName,occurredAt:new Date().toISOString(),reason:''};
    currentAudit.push(auditEvent as unknown as RawRecord); staged.set(STORAGE_KEYS.auditEvents,JSON.stringify(currentAudit));
    try{ for(const [key,value] of staged){this.storage.setItem(key,value);if(this.storage.getItem(key)!==value) throw new Error(`Verification failed for ${key}`);} return {successCount,failureCount:0,conflictCount:conflicts.length,failures:[],conflicts,rolledBack:false,rollbackSuccessful:true,preImportBackupKey}; }
    catch(error){ const rollbackFailures:string[]=[]; for(const [key,original] of originals){try{if(original===null)this.storage.removeItem(key);else this.storage.setItem(key,original);if(this.storage.getItem(key)!==original)rollbackFailures.push(`${key}: verification failed`);}catch(rollbackError){rollbackFailures.push(`${key}: ${rollbackError instanceof Error?rollbackError.message:'rollback failed'}`);}} const message=error instanceof Error?error.message:'Unexpected restore failure'; return {successCount:0,failureCount:Object.values(backup.moduleCounts??{}).reduce((sum,count)=>sum+count,0)+(backup.backupType==='full'?2:0),conflictCount:conflicts.length,failures:[`Restore failed: ${message}`,...rollbackFailures.map(item=>`Rollback ${item}`)],conflicts,rolledBack:true,rollbackSuccessful:rollbackFailures.length===0,preImportBackupKey}; }
  }
}
