import type { RepositoryRegistry } from '../repositories';
import type { EngagementFileLock } from '../types/models';
import { AppError, ValidationError } from '../utils/errors';
import { createMetadata, updateMetadata } from './helpers';
import type { ActivityService } from './ActivityService';
import type { AuditReviewWorkflowService } from './AuditReviewWorkflowService';
import type { AuditCompletionService } from './AuditCompletionService';
import type { AuditFindingService } from './AuditFindingService';
import { getListedGateBlockers } from './Phase4Service';

export class FileLockService{
 constructor(private readonly repositories:RepositoryRegistry,private readonly activity:ActivityService,private readonly review:AuditReviewWorkflowService,private readonly completion:AuditCompletionService,private readonly findings:AuditFindingService){}
 async records(engagementId:string){return (await this.repositories.engagementLocks.list({includeDeleted:true})).filter(r=>r.engagementId===engagementId);}
 async blockers(engagementId:string):Promise<string[]>{const errors:string[]=[]; const manager=await this.review.managerRecord(engagementId); const partner=await this.review.partnerRecord(engagementId); if(manager?.status!=='Completed')errors.push('Manager Review is not complete.'); if(!partner||!['Approved','Completed'].includes(partner.status))errors.push('Partner Review is not approved.'); errors.push(...await this.completion.blockers(engagementId)); const reports=(await this.repositories.reportVersions.list()).filter(r=>r.engagementId===engagementId); if(!reports.some(r=>r.status==='Final Approved'||r.status==='Issued'))errors.push('Final report is not approved.'); const issues=(await this.repositories.reportIssues.list()).filter(r=>r.engagementId===engagementId&&['Issued','Reissued'].includes(r.status)); if(!issues.length)errors.push('Final report has not been issued.'); const notes=(await this.repositories.reviewNotes.list()).filter(n=>n.engagementId===engagementId&&['Critical','High'].includes(n.severity)&&!['Cleared','Cancelled'].includes(n.status)); if(notes.length)errors.push('Critical/High review notes remain unresolved.'); if((await this.findings.unresolvedMaterial(engagementId)).length)errors.push('Material misstatements remain unresolved.'); const reps=(await this.repositories.representationLetters.list()).filter(r=>r.engagementId===engagementId&&r.mandatory&&!r.isDeleted); if(reps.length&&!reps.some(r=>r.status==='Signed'&&r.currentVersion))errors.push('Required Representation Letter is not signed.'); const progs=(await this.repositories.engagementProgrammes.list()).filter(p=>p.engagementId===engagementId&&p.mandatory); if(progs.some(p=>!['Completed','Reviewed'].includes(p.status)))errors.push('Required programme procedures are incomplete.'); const wps=(await this.repositories.workingPapers.list()).filter(w=>w.engagementId===engagementId); if(!wps.length||wps.some(w=>!['Manager Cleared','Partner Cleared','Final','Locked'].includes(w.status)))errors.push('Required Working Papers are not fully cleared.'); errors.push(...await getListedGateBlockers(this.repositories,engagementId)); return [...new Set(errors)];}
 async lock(engagementId:string,lockedById:string,lockReason:string,operatorName:string):Promise<EngagementFileLock>{const engagement=await this.repositories.engagements.getById(engagementId); if(!engagement)throw new AppError('Engagement not found.','NOT_FOUND'); if(engagement.status==='Locked')throw new ValidationError('Engagement is already locked.',['Use the Amendment workflow; silent unlock is not allowed.']); const errors=await this.blockers(engagementId); if(!lockedById)errors.push('Locked By is required.'); if(!lockReason.trim())errors.push('Lock Reason is required.'); if(errors.length)throw new ValidationError('Engagement file cannot be locked.',errors); const counts:Record<string,number>={}; for(const [key,repo] of Object.entries(this.repositories)){try{const rows=await (repo as {list(o?:{includeDeleted?:boolean}):Promise<Array<{engagementId?:string}>>}).list({includeDeleted:true}); counts[key]=rows.filter(r=>!('engagementId'in r)||r.engagementId===engagementId).length;}catch{counts[key]=0;}}
  const lock:EngagementFileLock={...createMetadata('Locked',operatorName),engagementId,lockDate:new Date().toISOString(),lockedById,lockReason,finalRecordCounts:counts,status:'Locked',notes:''}; const oldEngagements=await this.repositories.engagements.list({includeDeleted:true}); const oldLocks=await this.repositories.engagementLocks.list({includeDeleted:true}); const updated=updateMetadata({...engagement,status:'Locked' as const},operatorName);
  try{await this.repositories.engagementLocks.replaceAll([...oldLocks,lock]); await this.repositories.engagements.replaceAll(oldEngagements.map(e=>e.id===engagementId?updated:e));}catch(error){await this.repositories.engagementLocks.replaceAll(oldLocks); await this.repositories.engagements.replaceAll(oldEngagements); throw new AppError(`File lock failed and was rolled back. ${error instanceof Error?error.message:''}`,'ATOMIC_OPERATION_FAILED');}
  await this.activity.log({entityType:'Engagement File Lock',entityId:lock.id,action:'File Lock',previousStatus:engagement.status,newStatus:'Locked',operatorName,reason:lockReason,changedFieldSummary:`Engagement file locked with ${Object.values(counts).reduce((a,b)=>a+b,0)} recorded items.`}); return lock;}
}
