import {
  ACCEPTANCE_STATUSES, AUDIT_ASSERTIONS, AUDIT_RISK_STATUSES, AUDIT_RISK_TYPES, CLIENT_STATUSES,
  DEADLINE_STATUSES, DOCUMENT_REQUEST_STATUSES, ENGAGEMENT_LETTER_STATUSES, ENGAGEMENT_STATUSES,
  EVIDENCE_STATUSES, INDEPENDENCE_STATUSES, MATERIALITY_STATUSES, PLANNING_MEMO_STATUSES,
  PLANNING_MILESTONE_TYPES, PRIORITIES, PROGRAMME_STATUSES, RISK_RATINGS, SAMPLING_STATUSES,
  STAFF_ROLES, TASK_STATUSES, THREAT_RESPONSES, WORKING_PAPER_STATUSES, REVIEW_NOTE_STATUSES, REVIEW_LEVELS, REVIEW_SEVERITIES, COMPLETION_ITEM_STATUSES, AUDIT_FINDING_STATUSES, AUDIT_FINDING_TYPES, REPORT_VERSION_STATUSES, AUDIT_OPINIONS, MANAGEMENT_LETTER_STATUSES, REPRESENTATION_LETTER_STATUSES, REPORT_ISSUE_STATUSES, AMENDMENT_STATUSES, REVIEW_RECORD_STATUSES, LISTED_CHECKLIST_STATUSES, REGULATORY_DEADLINE_STATUSES, AUDIT_COMMITTEE_STATUSES, QUALITY_REVIEW_STATUSES, KAM_STATUSES, TAX_ASSIGNMENT_STATUSES, VAT_ASSIGNMENT_STATUSES, RJSC_ASSIGNMENT_STATUSES, ACCOUNTING_ASSIGNMENT_STATUSES, ADVISORY_ASSIGNMENT_STATUSES, TIMESHEET_STATUSES, EXPENSE_STATUSES, INVOICE_STATUSES, COLLECTION_STATUSES, COMMUNICATION_STATUSES, FOLLOW_UP_STATUSES
} from '../constants/statuses';
import { STORAGE_KEYS } from '../repositories/localStorage/keys';
import type { AppMeta, AppSettings } from '../types/models';

export const BACKUP_DATA_KEYS = [
  STORAGE_KEYS.clients, STORAGE_KEYS.clientContacts, STORAGE_KEYS.staff, STORAGE_KEYS.engagements,
  STORAGE_KEYS.engagementTeam, STORAGE_KEYS.engagementDeadlines, STORAGE_KEYS.tasks, STORAGE_KEYS.services,
  STORAGE_KEYS.clientCategories, STORAGE_KEYS.industries, STORAGE_KEYS.auditEvents, STORAGE_KEYS.acceptanceReviews,
  STORAGE_KEYS.independenceAssessments, STORAGE_KEYS.engagementLetters, STORAGE_KEYS.auditPlans, STORAGE_KEYS.planningMilestones,
  STORAGE_KEYS.auditRisks, STORAGE_KEYS.auditMateriality, STORAGE_KEYS.programmeTemplates, STORAGE_KEYS.engagementProgrammes,
  STORAGE_KEYS.workingPapers, STORAGE_KEYS.evidenceRegister, STORAGE_KEYS.samplingRegister, STORAGE_KEYS.documentRequests,
  STORAGE_KEYS.documentRequestItems, STORAGE_KEYS.documentRequestReminders, STORAGE_KEYS.reviewNotes, STORAGE_KEYS.auditCompletionItems,
  STORAGE_KEYS.auditFindings, STORAGE_KEYS.reportVersions, STORAGE_KEYS.managementLetters, STORAGE_KEYS.representationLetters, STORAGE_KEYS.reportIssues,
  STORAGE_KEYS.engagementLocks, STORAGE_KEYS.amendmentRequests, STORAGE_KEYS.managerReviewRecords, STORAGE_KEYS.partnerReviewRecords,
  STORAGE_KEYS.listedComplianceItems, STORAGE_KEYS.regulatoryDeadlines, STORAGE_KEYS.auditCommitteeCommunications, STORAGE_KEYS.qualityReviews, STORAGE_KEYS.keyAuditMatters,
  STORAGE_KEYS.taxAssignments, STORAGE_KEYS.vatAssignments, STORAGE_KEYS.rjscAssignments, STORAGE_KEYS.accountingAssignments, STORAGE_KEYS.advisoryAssignments,
  STORAGE_KEYS.timesheets, STORAGE_KEYS.expenses, STORAGE_KEYS.invoices, STORAGE_KEYS.collections, STORAGE_KEYS.communications, STORAGE_KEYS.followUps
] as const;

const isObject = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const isString = (value: unknown): value is string => typeof value === 'string';
const isBoolean = (value: unknown): value is boolean => typeof value === 'boolean';
const isFiniteNumber = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);
const isNonNegative = (value: unknown): value is number => isFiniteNumber(value) && value >= 0;
const isPositive = (value: unknown): value is number => isFiniteNumber(value) && value > 0;
const isPositiveInteger = (value: unknown): value is number => Number.isInteger(value) && Number(value) > 0;
const inValues = (value: unknown, values: readonly string[]): boolean => isString(value) && values.includes(value);
const isStringArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(isString);
const isIsoDate = (value: unknown, allowEmpty = true): boolean => {
  if (allowEmpty && value === '') return true;
  if (!isString(value) || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const date = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value;
};
const isIsoDateTime = (value: unknown): boolean => isString(value) && !Number.isNaN(Date.parse(value));

function requireBase(record: Record<string, unknown>, path: string, statuses: readonly string[], errors: string[]): void {
  if (!isString(record.id) || !record.id.trim()) errors.push(`${path}.id must be a non-empty string.`);
  if (!isIsoDateTime(record.createdAt)) errors.push(`${path}.createdAt must be a valid date-time.`);
  if (!isIsoDateTime(record.updatedAt)) errors.push(`${path}.updatedAt must be a valid date-time.`);
  if (!isString(record.createdByName) || !record.createdByName.trim()) errors.push(`${path}.createdByName is required.`);
  if (!isString(record.updatedByName) || !record.updatedByName.trim()) errors.push(`${path}.updatedByName is required.`);
  if (!isPositiveInteger(record.recordVersion)) errors.push(`${path}.recordVersion must be a positive integer.`);
  if (!inValues(record.status, statuses)) errors.push(`${path}.status is invalid.`);
  if (!isBoolean(record.isDeleted)) errors.push(`${path}.isDeleted must be boolean.`);
}
function strings(record: Record<string, unknown>, path: string, fields: string[], errors: string[]): void { for (const field of fields) if (!isString(record[field])) errors.push(`${path}.${field} must be a string.`); }
function required(record: Record<string, unknown>, path: string, fields: string[], errors: string[]): void { for (const field of fields) if (!isString(record[field]) || !String(record[field]).trim()) errors.push(`${path}.${field} is required.`); }
function dates(record: Record<string, unknown>, path: string, fields: string[], errors: string[], allowEmpty = true): void { for (const field of fields) if (!isIsoDate(record[field], allowEmpty)) errors.push(`${path}.${field} must be a valid date${allowEmpty ? ' or empty' : ''}.`); }
function stringArray(record: Record<string, unknown>, path: string, field: string, errors: string[], allowed?: readonly string[]): void {
  if (!isStringArray(record[field])) errors.push(`${path}.${field} must be an array of strings.`);
  else if (allowed && (record[field] as string[]).some(value => !allowed.includes(value))) errors.push(`${path}.${field} contains an invalid value.`);
}

function validateClient(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,CLIENT_STATUSES,e); required(r,p,['clientCode','legalName'],e); strings(r,p,['tradeName','entityType','industryId','clientCategoryId','tin','bin','registrationNumber','registeredAddress','businessAddress','primaryPhone','primaryEmail','website','responsiblePartnerId','responsibleManagerId','notes'],e);
  if (!isIsoDate(r.financialYearEnd)) e.push(`${p}.financialYearEnd must be a valid date or empty.`); if (!isBoolean(r.isListedPie)) e.push(`${p}.isListedPie must be boolean.`); if (!inValues(r.riskRating,RISK_RATINGS)) e.push(`${p}.riskRating is invalid.`);
}
function validateContact(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,['Active','Inactive'],e); required(r,p,['clientId','name'],e); strings(r,p,['designation','department','email','phone','notes'],e); if (!inValues(r.communicationPreference,['Email','Phone','Any'])) e.push(`${p}.communicationPreference is invalid.`); if (!isBoolean(r.isPrimary)||!isBoolean(r.isActive)) e.push(`${p}.isPrimary and isActive must be boolean.`);
}
function validateStaff(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,['Active','Inactive'],e); required(r,p,['staffCode','fullName'],e); strings(r,p,['designation','email','phone','notes'],e); if (!inValues(r.role,STAFF_ROLES)) e.push(`${p}.role is invalid.`); if (!isNonNegative(r.weeklyCapacityHours)) e.push(`${p}.weeklyCapacityHours must be nonnegative.`); if (!isIsoDate(r.joinDate)) e.push(`${p}.joinDate must be a valid date or empty.`); if (!isBoolean(r.isActive)) e.push(`${p}.isActive must be boolean.`);
}
function validateFinancial(value: unknown, p: string, e: string[]): void {
  if (!isObject(value)) { e.push(`${p} must be an object.`); return; }
  for (const f of ['proposedFee','approvedFee','budgetHours','amountBilled','amountCollected','outstandingAmount']) if (!isNonNegative(value[f])) e.push(`${p}.${f} must be nonnegative.`);
  if (!inValues(value.billingStatus,['Not Started','Partially Billed','Fully Billed','Collected','On Hold'])) e.push(`${p}.billingStatus is invalid.`);
  if (isFiniteNumber(value.amountCollected)&&isFiniteNumber(value.amountBilled)&&value.amountCollected>value.amountBilled) e.push(`${p}.amountCollected cannot exceed amountBilled.`);
  if (isFiniteNumber(value.amountBilled)&&isFiniteNumber(value.amountCollected)&&value.outstandingAmount!==value.amountBilled-value.amountCollected) e.push(`${p}.outstandingAmount is inconsistent.`);
}
function validateEngagement(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,ENGAGEMENT_STATUSES,e); required(r,p,['engagementCode','clientId','serviceType','engagementType'],e); strings(r,p,['responsiblePartnerId','responsibleManagerId','scopeSummary','notes'],e); dates(r,p,['financialPeriodStart','financialPeriodEnd','startDate','targetCompletionDate','reportingDeadline'],e);
  if (isString(r.financialPeriodStart)&&isString(r.financialPeriodEnd)&&r.financialPeriodStart&&r.financialPeriodEnd&&r.financialPeriodEnd<r.financialPeriodStart) e.push(`${p}.financialPeriodEnd cannot precede financialPeriodStart.`); if (isString(r.startDate)&&isString(r.targetCompletionDate)&&r.startDate&&r.targetCompletionDate&&r.targetCompletionDate<r.startDate) e.push(`${p}.targetCompletionDate cannot precede startDate.`);
  if (!inValues(r.riskRating,RISK_RATINGS)) e.push(`${p}.riskRating is invalid.`); if (!inValues(r.priority,PRIORITIES)) e.push(`${p}.priority is invalid.`); if (!isBoolean(r.listedPieWorkflowRequired)) e.push(`${p}.listedPieWorkflowRequired must be boolean.`); validateFinancial(r.financial,`${p}.financial`,e);
}
function validateTeam(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,['Active','Inactive'],e); required(r,p,['engagementId','staffId','assignmentRole'],e); strings(r,p,['responsibilityNotes'],e); if (r.responsibilityArea!==undefined&&!isString(r.responsibilityArea)) e.push(`${p}.responsibilityArea must be a string.`); if (!isPositive(r.estimatedHours)) e.push(`${p}.estimatedHours must be positive.`); dates(r,p,['startDate','endDate'],e); if (isString(r.startDate)&&isString(r.endDate)&&r.startDate&&r.endDate&&r.endDate<r.startDate) e.push(`${p}.endDate cannot precede startDate.`); if (!isBoolean(r.isActive)) e.push(`${p}.isActive must be boolean.`);
}
function validateTask(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,TASK_STATUSES,e); required(r,p,['title'],e); strings(r,p,['clientId','engagementId','assigneeId','reviewerId','blockerReason','description'],e); dates(r,p,['startDate','dueDate','completionDate'],e); if (!inValues(r.taskType,['Internal','Client','Engagement'])) e.push(`${p}.taskType is invalid.`); if (!inValues(r.priority,PRIORITIES)) e.push(`${p}.priority is invalid.`); if (!isNonNegative(r.estimatedHours)) e.push(`${p}.estimatedHours must be nonnegative.`); if (r.status==='Blocked'&&!String(r.blockerReason??'').trim()) e.push(`${p}.blockerReason is required when Blocked.`); if (r.status==='Completed'&&!r.completionDate) e.push(`${p}.completionDate is required when Completed.`);
}
function validateDeadline(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,DEADLINE_STATUSES,e); required(r,p,['clientId','engagementId','deadlineType','description','dueDate'],e); strings(r,p,['ownerId','changeReason'],e); dates(r,p,['dueDate'],e,false); dates(r,p,['completionDate'],e); if (!inValues(r.priority,PRIORITIES)) e.push(`${p}.priority is invalid.`); if (r.status==='Completed'&&!r.completionDate) e.push(`${p}.completionDate is required when Completed.`);
}
function validateMaster(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,['Active','Inactive'],e); required(r,p,['code','name'],e); strings(r,p,['description'],e); if (!isBoolean(r.isActive)) e.push(`${p}.isActive must be boolean.`); }
function validateAuditEvent(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,['Recorded'],e); required(r,p,['entityType','entityId','action','operatorName','occurredAt'],e); strings(r,p,['previousStatus','newStatus','changedFieldSummary','reason'],e); if (!isIsoDateTime(r.occurredAt)) e.push(`${p}.occurredAt must be a valid date-time.`); }
function validateAcceptance(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,ACCEPTANCE_STATUSES,e); required(r,p,['engagementId'],e); strings(r,p,['clientBackgroundSummary','natureOfBusiness','ownershipManagementSummary','reasonForAppointment','previousAuditorDetails','managementIntegrityAssessment','financialReportingFramework','regulatoryEnvironment','competenceResourcesAvailable','ethicalThreatsIdentified','safeguardsApplied','acceptanceRecommendation','managerReviewerId','partnerApproverId','rejectionReason','notes'],e); dates(r,p,['managerReviewDate','partnerApprovalDate'],e); if (!inValues(r.reviewType,['New Client Acceptance','Existing Client Continuance'])) e.push(`${p}.reviewType is invalid.`); if (!inValues(r.engagementRiskRating,RISK_RATINGS)) e.push(`${p}.engagementRiskRating is invalid.`); if (r.status==='Rejected'&&!String(r.rejectionReason??'').trim()) e.push(`${p}.rejectionReason is required when Rejected.`); if (r.partnerApprovalDate&&!r.managerReviewDate) e.push(`${p}.managerReviewDate is required before partnerApprovalDate.`); if (isString(r.managerReviewDate)&&isString(r.partnerApprovalDate)&&r.managerReviewDate&&r.partnerApprovalDate&&r.partnerApprovalDate<r.managerReviewDate) e.push(`${p}.partnerApprovalDate cannot precede managerReviewDate.`);
}
function validateIndependence(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,INDEPENDENCE_STATUSES,e); required(r,p,['engagementId','assessmentDate'],e); strings(r,p,['assessedById','threatDescription','safeguards','conclusion','notes'],e); dates(r,p,['assessmentDate'],e,false); const tf=['financialInterestThreat','businessRelationshipThreat','familyPersonalRelationshipThreat','employmentRelationshipThreat','longAssociationThreat','nonAuditServiceThreat','feeDependencyThreat','litigationThreat','otherThreat']; for (const f of [...tf,'conflictFound']) if (!inValues(r[f],THREAT_RESPONSES)) e.push(`${p}.${f} is invalid.`); if (!isBoolean(r.managerReviewed)||!isBoolean(r.partnerCleared)) e.push(`${p}.managerReviewed and partnerCleared must be boolean.`); const has=tf.some(f=>r[f]==='Yes'); if (has&&!String(r.threatDescription??'').trim()) e.push(`${p}.threatDescription is required when a threat is Yes.`); if (has&&!String(r.safeguards??'').trim()) e.push(`${p}.safeguards are required when a threat is Yes.`);
}
function validateLetter(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,ENGAGEMENT_LETTER_STATUSES,e); required(r,p,['engagementId','letterReference'],e); if (!isPositiveInteger(r.letterVersion)) e.push(`${p}.letterVersion must be positive.`); strings(r,p,['scopeSummary','responsibilitiesSummary','reportingFramework','feeTermsSummary','clientSignatory','fileReference','notes'],e); dates(r,p,['draftDate','sentToClientDate','clientAcceptanceDate','effectiveDate','expiryDate'],e); if (!isBoolean(r.signedByFirm)||!isBoolean(r.signedByClient)) e.push(`${p}.signature confirmations must be boolean.`); if (r.status==='Accepted'&&(!r.clientAcceptanceDate||r.signedByFirm!==true||r.signedByClient!==true)) e.push(`${p}.Accepted letter requires acceptance date and both signatures.`);
}
function validatePlan(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,PLANNING_MEMO_STATUSES,e); required(r,p,['engagementId'],e); strings(r,p,['entityUnderstanding','businessModelSummary','industryRegulatoryFactors','ownershipGovernance','keyManagement','financialReportingFramework','significantAccountingPolicies','priorYearAuditIssues','currentYearSignificantChanges','internalControlEnvironmentSummary','useOfExperts','useOfInternalAudit','componentBranchConsiderations','goingConcernPreliminaryAssessment','fraudConsiderations','relatedPartyConsiderations','plannedAuditApproach','keyMilestones','reportingDeliverables','managerReviewerId','partnerApproverId','notes'],e); dates(r,p,['managerReviewDate','partnerApprovalDate'],e); if (r.partnerApprovalDate&&!r.managerReviewDate) e.push(`${p}.managerReviewDate is required before partnerApprovalDate.`); if (isString(r.managerReviewDate)&&isString(r.partnerApprovalDate)&&r.managerReviewDate&&r.partnerApprovalDate&&r.partnerApprovalDate<r.managerReviewDate) e.push(`${p}.partnerApprovalDate cannot precede managerReviewDate.`);
}
function validateMilestone(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,DEADLINE_STATUSES,e); required(r,p,['engagementId','milestoneType','description','dueDate'],e); strings(r,p,['ownerId','changeReason'],e); dates(r,p,['dueDate'],e,false); dates(r,p,['completionDate'],e); if (!inValues(r.milestoneType,PLANNING_MILESTONE_TYPES)) e.push(`${p}.milestoneType is invalid.`); if (!inValues(r.priority,PRIORITIES)) e.push(`${p}.priority is invalid.`); }
function validateRisk(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,AUDIT_RISK_STATUSES,e); required(r,p,['engagementId','riskCode','auditArea','riskTitle'],e); strings(r,p,['riskDescription','riskSource','financialStatementCaption','plannedAuditResponse','assignedStaffId','preparedById','managerReviewerId','partnerReviewerId','conclusion','notes'],e); if (!inValues(r.riskType,AUDIT_RISK_TYPES)) e.push(`${p}.riskType is invalid.`); stringArray(r,p,'assertions',e,AUDIT_ASSERTIONS); for (const f of ['likelihood','impact','inherentRiskRating','residualRiskRating']) if (!inValues(r[f],RISK_RATINGS)) e.push(`${p}.${f} is invalid.`); for (const f of ['controlReliancePlanned','significantRisk','fraudRisk']) if (!isBoolean(r[f])) e.push(`${p}.${f} must be boolean.`); if (r.riskType==='Assertion Level'&&Array.isArray(r.assertions)&&r.assertions.length===0) e.push(`${p}.assertions is required for Assertion Level risk.`); if (['Manager Review','Partner Review','Approved','Closed'].includes(String(r.status))&&!String(r.plannedAuditResponse??'').trim()) e.push(`${p}.plannedAuditResponse is required before review.`);
}
function validateMateriality(r: Record<string, unknown>, p: string, e: string[]): void {
  requireBase(r,p,MATERIALITY_STATUSES,e); required(r,p,['engagementId','benchmark'],e); if (!isPositiveInteger(r.version)) e.push(`${p}.version must be positive.`); for (const f of ['benchmarkAmount','selectedPercentage','performanceMaterialityPercentage']) if (!isPositive(r[f])) e.push(`${p}.${f} must be positive.`); for (const f of ['overallMateriality','performanceMateriality','clearlyTrivialPercentage','clearlyTrivialThreshold','priorYearMateriality']) if (!isNonNegative(r[f])) e.push(`${p}.${f} must be nonnegative.`); if (isFiniteNumber(r.performanceMateriality)&&isFiniteNumber(r.overallMateriality)&&r.performanceMateriality>r.overallMateriality) e.push(`${p}.performanceMateriality cannot exceed overallMateriality.`); if (isFiniteNumber(r.clearlyTrivialThreshold)&&isFiniteNumber(r.performanceMateriality)&&r.clearlyTrivialThreshold>r.performanceMateriality) e.push(`${p}.clearlyTrivialThreshold cannot exceed performanceMateriality.`); if (!isBoolean(r.specificMaterialityRequired)) e.push(`${p}.specificMaterialityRequired must be boolean.`); strings(r,p,['specificMaterialityDetails','rationaleForBenchmark','rationaleForPercentage','significantChanges','preparedById','managerReviewerId','partnerApproverId','notes'],e); dates(r,p,['managerReviewDate','partnerApprovalDate'],e); if (r.partnerApprovalDate&&!r.managerReviewDate) e.push(`${p}.managerReviewDate is required before partnerApprovalDate.`); if (isString(r.managerReviewDate)&&isString(r.partnerApprovalDate)&&r.managerReviewDate&&r.partnerApprovalDate&&r.partnerApprovalDate<r.managerReviewDate) e.push(`${p}.partnerApprovalDate cannot precede managerReviewDate.`);
}
function validateTemplate(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,['Active','Inactive'],e); required(r,p,['templateCode','templateName','procedureCode','procedureDescription'],e); strings(r,p,['auditArea','applicableIndustryId','applicableClientType','objective','defaultAssigneeRole','notes'],e); if (!isBoolean(r.mandatory)||!isBoolean(r.isActive)) e.push(`${p}.mandatory and isActive must be boolean.`); if (!isPositiveInteger(r.version)) e.push(`${p}.version must be positive.`); if (r.defaultAssigneeRole&&!inValues(r.defaultAssigneeRole,STAFF_ROLES)) e.push(`${p}.defaultAssigneeRole is invalid.`); }
function validateProgramme(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,PROGRAMME_STATUSES,e); required(r,p,['engagementId','procedureCode','procedureDescription'],e); strings(r,p,['templateId','programmeArea','objective','assigneeId','reviewerId','dueDate','notApplicableReason','completionComment','managerReviewComment','notes'],e); stringArray(r,p,'linkedRiskIds',e); stringArray(r,p,'assertionCoverage',e,AUDIT_ASSERTIONS); if (!isBoolean(r.mandatory)) e.push(`${p}.mandatory must be boolean.`); if (r.dueDate&&!isIsoDate(r.dueDate)) e.push(`${p}.dueDate is invalid.`); if (r.status==='Not Applicable'&&r.mandatory===true&&!String(r.notApplicableReason??'').trim()) e.push(`${p}.notApplicableReason is required for mandatory procedure.`); if (r.status==='Completed'&&!String(r.completionComment??'').trim()) e.push(`${p}.completionComment is required when Completed.`); }
function validateWorkingPaper(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,WORKING_PAPER_STATUSES,e); required(r,p,['engagementId','wpReference','title'],e); strings(r,p,['auditArea','objective','linkedProgrammeProcedureId','procedurePerformed','populationDescription','sampleDescription','evidenceSummary','result','exceptions','conclusion','preparedById','reviewerId','localPhysicalFileReference','notes'],e); stringArray(r,p,'linkedRiskIds',e); stringArray(r,p,'assertions',e,AUDIT_ASSERTIONS); stringArray(r,p,'crossReferences',e); dates(r,p,['preparedDate','reviewDate'],e); if (isString(r.preparedDate)&&isString(r.reviewDate)&&r.preparedDate&&r.reviewDate&&r.preparedDate>r.reviewDate) e.push(`${p}.preparedDate cannot be after reviewDate.`); }
function validateEvidence(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,EVIDENCE_STATUSES,e); required(r,p,['engagementId','evidenceReference','description'],e); strings(r,p,['workingPaperId','evidenceType','source','fileName','localPhysicalFileReference','acceptedById','rejectionReason','notes'],e); dates(r,p,['sourceDate','receivedDate','acceptanceDate'],e); if (!inValues(r.reliabilityRating,RISK_RATINGS)) e.push(`${p}.reliabilityRating is invalid.`); if (!isPositiveInteger(r.version)) e.push(`${p}.version must be positive.`); if (r.status==='Accepted'&&(!r.workingPaperId||!r.acceptedById||!r.acceptanceDate)) e.push(`${p}.Accepted evidence requires Working Paper, Accepted By and Acceptance Date.`); if (r.status==='Rejected'&&!String(r.rejectionReason??'').trim()) e.push(`${p}.rejectionReason is required when Rejected.`); }
function validateSampling(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,SAMPLING_STATUSES,e); required(r,p,['engagementId','workingPaperId','population'],e); strings(r,p,['samplingMethod','selectionBasis','conclusion','preparedById','reviewerId','notes'],e); if (!isPositiveInteger(r.populationSize)||!isPositiveInteger(r.sampleSize)) e.push(`${p}.populationSize and sampleSize must be positive integers.`); if (isFiniteNumber(r.sampleSize)&&isFiniteNumber(r.populationSize)&&r.sampleSize>r.populationSize) e.push(`${p}.sampleSize cannot exceed populationSize.`); if (!Number.isInteger(r.exceptionsFound)||Number(r.exceptionsFound)<0||Number(r.exceptionsFound)>Number(r.sampleSize)) e.push(`${p}.exceptionsFound is invalid.`); }
function validateRequest(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,DOCUMENT_REQUEST_STATUSES,e); required(r,p,['engagementId','requestReference','requestTitle'],e); strings(r,p,['clientContactId','responsibleStaffId','waiverReason','notes'],e); dates(r,p,['sentDate','overallDueDate'],e); if (!inValues(r.priority,PRIORITIES)) e.push(`${p}.priority is invalid.`); if (r.status==='Sent'&&!r.sentDate) e.push(`${p}.sentDate is required when Sent.`); if (r.status==='Waived'&&!String(r.waiverReason??'').trim()) e.push(`${p}.waiverReason is required when Waived.`); }
function validateRequestItem(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,DOCUMENT_REQUEST_STATUSES,e); required(r,p,['requestId','itemCode','description'],e); strings(r,p,['category','period','assignedClientContactId','fileName','localPhysicalFileReference','reviewResult','rejectionReason','linkedWorkingPaperId','waiverReason','notes'],e); dates(r,p,['dueDate','receivedDate'],e); if (!inValues(r.priority,PRIORITIES)) e.push(`${p}.priority is invalid.`); if (!isPositiveInteger(r.version)) e.push(`${p}.version must be positive.`); if (['Received','Under Review','Accepted','Rejected','Resubmission Required'].includes(String(r.status))&&!r.receivedDate) e.push(`${p}.receivedDate is required for received/review statuses.`); if (r.status==='Rejected'&&!String(r.rejectionReason??'').trim()) e.push(`${p}.rejectionReason is required when Rejected.`); if (r.status==='Waived'&&!String(r.waiverReason??'').trim()) e.push(`${p}.waiverReason is required when Waived.`); }
function validateReminder(r: Record<string, unknown>, p: string, e: string[]): void { requireBase(r,p,['Recorded'],e); required(r,p,['requestId','reminderDate','note'],e); strings(r,p,['requestItemId','recipient'],e); dates(r,p,['reminderDate'],e,false); if (!inValues(r.method,['Manual Note','Phone','Meeting','Other'])) e.push(`${p}.method is invalid.`); }


function validateReviewNote(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REVIEW_NOTE_STATUSES,e);required(r,p,['reviewNoteReference','engagementId','relatedRecordType','relatedRecordId','reviewNote','raisedById','raisedDate'],e);strings(r,p,['assignedToId','response','responseById','responseDate','reviewerRecheckComment','clearedById','clearedDate','reopenReason','cancellationReason','notes'],e);if(!inValues(r.reviewLevel,REVIEW_LEVELS))e.push(`${p}.reviewLevel is invalid.`);if(!inValues(r.severity,REVIEW_SEVERITIES))e.push(`${p}.severity is invalid.`);dates(r,p,['raisedDate','responseDate','clearedDate'],e);if(r.status==='Response Submitted'&&(!String(r.response??'').trim()||!r.responseById))e.push(`${p}.Response Submitted requires response and responder.`);if(r.status==='Cleared'&&(!String(r.reviewerRecheckComment??'').trim()||!r.clearedById||!r.clearedDate))e.push(`${p}.Cleared requires reviewer comment, cleared by and date.`);if(r.status==='Reopened'&&!String(r.reopenReason??'').trim())e.push(`${p}.Reopened requires reason.`);if(r.status==='Cancelled'&&!String(r.cancellationReason??'').trim())e.push(`${p}.Cancelled requires reason.`);}
function validateCompletionItem(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,COMPLETION_ITEM_STATUSES,e);required(r,p,['engagementId','checklistCode','checklistItem'],e);strings(r,p,['responsiblePersonId','evidenceReference','completionComment','completedById','completionDate','reviewerId','reviewDate','notApplicableReason','notes'],e);if(!isBoolean(r.required))e.push(`${p}.required must be boolean.`);dates(r,p,['completionDate','reviewDate'],e);if(r.status==='Not Applicable'&&!String(r.notApplicableReason??'').trim())e.push(`${p}.Not Applicable requires reason.`);if(r.status==='Completed'&&!String(r.evidenceReference??'').trim()&&!String(r.completionComment??'').trim())e.push(`${p}.Completed requires evidence/reference or comment.`);}
function validateFinding(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,AUDIT_FINDING_STATUSES,e);required(r,p,['engagementId','findingReference','description'],e);strings(r,p,['auditArea','criteria','condition','cause','effect','recommendation','managementResponse','linkedRiskId','linkedWorkingPaperId','conclusion','notes'],e);if(!inValues(r.findingType,AUDIT_FINDING_TYPES))e.push(`${p}.findingType is invalid.`);if(!isNonNegative(r.amount)||!isNonNegative(r.uncorrectedAmount))e.push(`${p}.amounts must be nonnegative.`);if(!isBoolean(r.corrected)||!isBoolean(r.reportable)||!isBoolean(r.partnerReviewed))e.push(`${p}.finding flags must be boolean.`);if(!inValues(r.materialityImpact,RISK_RATINGS)||!inValues(r.severity,REVIEW_SEVERITIES))e.push(`${p}.risk/severity is invalid.`);if(r.uncorrectedAmount!==(r.corrected?0:r.amount))e.push(`${p}.uncorrectedAmount is inconsistent.`);}
function validateReportVersion(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REPORT_VERSION_STATUSES,e);required(r,p,['engagementId','reportType'],e);if(!isPositiveInteger(r.versionNumber))e.push(`${p}.versionNumber must be positive.`);dates(r,p,['versionDate','managerReviewDate','partnerApprovalDate'],e);strings(r,p,['financialStatementVersionReference','basisSummary','emphasisOfMatter','otherMatter','goingConcernSection','otherInformationSection','responsibilitiesSummary','auditorResponsibilitiesSummary','managerReviewerId','partnerApproverId','fileReference','returnReason','notes'],e);if(!inValues(r.proposedOpinion,AUDIT_OPINIONS))e.push(`${p}.proposedOpinion is invalid.`);if(!isBoolean(r.currentVersion)||!isBoolean(r.finalVersion))e.push(`${p}.version flags must be boolean.`);if(r.partnerApprovalDate&&!r.managerReviewDate)e.push(`${p}.managerReviewDate is required before partnerApprovalDate.`);if(r.managerReviewDate&&r.partnerApprovalDate&&r.partnerApprovalDate<r.managerReviewDate)e.push(`${p}.partnerApprovalDate cannot precede managerReviewDate.`);}
function validateManagementLetter(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,MANAGEMENT_LETTER_STATUSES,e);required(r,p,['engagementId','reference'],e);if(!isPositiveInteger(r.version))e.push(`${p}.version must be positive.`);dates(r,p,['letterDate','managerReviewDate','partnerApprovalDate'],e);stringArray(r,p,'findingIds',e);strings(r,p,['recipient','managerReviewerId','partnerApproverId','clientResponseStatus','fileReference','notes'],e);if(!isBoolean(r.currentVersion)||!isBoolean(r.finalVersion))e.push(`${p}.version flags must be boolean.`);}
function validateRepresentationLetter(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REPRESENTATION_LETTER_STATUSES,e);required(r,p,['engagementId','reference'],e);if(!isPositiveInteger(r.version))e.push(`${p}.version must be positive.`);dates(r,p,['draftDate','sentDate','signedDate'],e);strings(r,p,['signatory','representationPeriod','fileReference','notes'],e);if(!isBoolean(r.currentVersion)||!isBoolean(r.mandatory))e.push(`${p}.currentVersion/mandatory must be boolean.`);if(r.status==='Signed'&&(!r.signedDate||!String(r.signatory??'').trim()))e.push(`${p}.Signed requires signedDate and signatory.`);}
function validateReportIssue(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REPORT_ISSUE_STATUSES,e);required(r,p,['engagementId','finalReportVersionId','issueReference'],e);dates(r,p,['reportDate','issueDate'],e,false);strings(r,p,['signedByPartnerId','recipient','deliveryMethod','financialStatementVersion','finalFileReference','notes'],e);if(!inValues(r.opinionType,AUDIT_OPINIONS))e.push(`${p}.opinionType is invalid.`);if(!isBoolean(r.managementLetterIssued)||!isBoolean(r.representationLetterReceived))e.push(`${p}.issue flags must be boolean.`);if(isString(r.issueDate)&&isString(r.reportDate)&&r.issueDate<r.reportDate)e.push(`${p}.issueDate cannot precede reportDate.`);}
function validateFileLock(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,['Locked','Re-Locked'],e);required(r,p,['engagementId','lockDate','lockedById','lockReason'],e);if(!isIsoDateTime(r.lockDate))e.push(`${p}.lockDate must be date-time.`);if(!isObject(r.finalRecordCounts))e.push(`${p}.finalRecordCounts must be object.`);strings(r,p,['notes'],e);}
function validateAmendment(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,AMENDMENT_STATUSES,e);required(r,p,['engagementId','amendmentReference','requestedById','requestDate','reason','affectedRecordType','affectedRecordId','proposedChange'],e);strings(r,p,['managerRecommendation','partnerDecision','approvalDate','completionDate','reLockDate','notes'],e);dates(r,p,['requestDate','approvalDate','completionDate','reLockDate'],e);if(!inValues(r.amendmentStatus,AMENDMENT_STATUSES)||r.status!==r.amendmentStatus)e.push(`${p}.amendment status is invalid/inconsistent.`);}
function validateManagerReview(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REVIEW_RECORD_STATUSES,e);required(r,p,['engagementId'],e);strings(r,p,['managerId','completionDate','reopenReason','returnComment','notes'],e);dates(r,p,['completionDate'],e);if(!isNonNegative(r.readinessPercentage)||Number(r.readinessPercentage)>100)e.push(`${p}.readinessPercentage must be 0-100.`);stringArray(r,p,'blockingItems',e);}
function validatePartnerReview(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REVIEW_RECORD_STATUSES,e);required(r,p,['engagementId'],e);strings(r,p,['partnerId','approvalDate','selectedReportVersionId','decisionComment','reopenReason','notes'],e);dates(r,p,['approvalDate'],e);if(!isNonNegative(r.readinessPercentage)||Number(r.readinessPercentage)>100)e.push(`${p}.readinessPercentage must be 0-100.`);stringArray(r,p,'blockingItems',e);}


function validateListedCompliance(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,LISTED_CHECKLIST_STATUSES,e);required(r,p,['engagementId','checklistCode','requirement','category'],e);strings(r,p,['ownerId','dueDate','evidenceReference','completionComment','completedById','completionDate','reviewerId','reviewDate','exceptionReason','notApplicableReason','notes'],e);dates(r,p,['dueDate','completionDate','reviewDate'],e);if(!isBoolean(r.required))e.push(`${p}.required must be boolean.`);}
function validateRegulatoryDeadline(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,REGULATORY_DEADLINE_STATUSES,e);required(r,p,['clientId','engagementId','regulatoryBody','requirement','dueDate'],e);strings(r,p,['reportingPeriod','responsiblePersonId','submissionCompletionDate','reference','changeReason','notes'],e);dates(r,p,['dueDate','submissionCompletionDate'],e);if(!inValues(r.priority,PRIORITIES))e.push(`${p}.priority is invalid.`);}
function validateCommittee(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,AUDIT_COMMITTEE_STATUSES,e);required(r,p,['engagementId','communicationReference','communicationStage','subject'],e);strings(r,p,['communicationDate','meetingDate','recipient','followUpActions','responsiblePersonId','fileReference','notes'],e);dates(r,p,['communicationDate','meetingDate'],e);for(const f of ['significantRisksCommunicated','independenceCommunicated','uncorrectedMisstatementsCommunicated','controlDeficienciesCommunicated','keyAuditMattersDiscussed','goingConcernDiscussed'])if(!isBoolean(r[f]))e.push(`${p}.${f} must be boolean.`);if(!inValues(r.communicationStage,['Planning','Interim','Completion','Special Matter']))e.push(`${p}.communicationStage is invalid.`);}
function validateQualityReview(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,QUALITY_REVIEW_STATUSES,e);required(r,p,['engagementId'],e);strings(r,p,['qualityReviewerId','reviewStartDate','reviewCompletionDate','reviewFindings','reviewerConclusion','managerResponse','partnerResponse','approvalDate','waiverReason','notes'],e);dates(r,p,['reviewStartDate','reviewCompletionDate','approvalDate'],e);for(const f of ['significantJudgementsReviewed','significantRisksReviewed','materialityReviewed','independenceReviewed','goingConcernReviewed','keyAuditMattersReviewed','financialStatementsReviewed','auditOpinionReviewed','uncorrectedMisstatementsReviewed'])if(!isBoolean(r[f]))e.push(`${p}.${f} must be boolean.`);}
function validateKam(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,KAM_STATUSES,e);required(r,p,['engagementId','kamReference','title'],e);strings(r,p,['relatedSignificantRiskId','whyMatterWasSignificant','howMatterWasAddressed','auditCommitteeDiscussionReference','proposedReportWording','managerReviewerId','partnerApproverId','qualityReviewerId','decisionReason','notes'],e);stringArray(r,p,'relatedWorkingPaperIds',e);}
function validateTax(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,TAX_ASSIGNMENT_STATUSES,e);required(r,p,['engagementId','assessmentYear','taxAssignmentType','filingDeadline'],e);strings(r,p,['taxpayerTin','documentsRequired','computationVersion','clientConfirmationDate','managerReviewDate','submissionDate','submissionReference','assessmentHearingDate','responsibleStaffId','managerReviewerId','notes'],e);dates(r,p,['filingDeadline','clientConfirmationDate','managerReviewDate','submissionDate','assessmentHearingDate'],e);for(const f of ['taxableIncome','taxLiability','advanceTax','withholdingTax'])if(!isNonNegative(r[f]))e.push(`${p}.${f} must be nonnegative.`);if(!isFiniteNumber(r.taxPayableRefundable))e.push(`${p}.taxPayableRefundable must be numeric.`);}
function validateVat(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,VAT_ASSIGNMENT_STATUSES,e);required(r,p,['engagementId','vatPeriod','bin','assignmentType','filingDeadline'],e);strings(r,p,['reconciliationStatus','clientApprovalDate','managerReviewDate','submissionDate','submissionReference','noticeReference','noticeResponseDeadline','responsibleStaffId','managerReviewerId','notes'],e);dates(r,p,['filingDeadline','clientApprovalDate','managerReviewDate','submissionDate','noticeResponseDeadline'],e);for(const f of ['outputVat','inputVat','adjustments','netVatPayableRefundable'])if(!isFiniteNumber(r[f]))e.push(`${p}.${f} must be numeric.`);}
function validateRjsc(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,RJSC_ASSIGNMENT_STATUSES,e);required(r,p,['engagementId','companyRegistrationNumber','filingType','filingPeriod'],e);strings(r,p,['filingDeadline','documentsRequired','clientSignOffDate','filingDate','filingReference','acceptanceDate','responsibleStaffId','reviewerId','notes'],e);dates(r,p,['filingDeadline','clientSignOffDate','filingDate','acceptanceDate'],e);}
function validateAccounting(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,ACCOUNTING_ASSIGNMENT_STATUSES,e);required(r,p,['engagementId','accountingPeriodStart','accountingPeriodEnd','scope'],e);strings(r,p,['processingStatus','bankReconciliationStatus','unreconciledItems','trialBalanceStatus','draftAccountsVersion','clientReviewDate','finalAccountsVersion','responsibleStaffId','reviewerId','reviewerApprovalDate','notes'],e);dates(r,p,['accountingPeriodStart','accountingPeriodEnd','clientReviewDate','reviewerApprovalDate'],e,false);if(!isBoolean(r.openingBalanceConfirmed)||!isBoolean(r.recordsReceived))e.push(`${p}.accounting flags must be boolean.`);}
function validateAdvisory(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,ADVISORY_ASSIGNMENT_STATUSES,e);required(r,p,['engagementId','advisoryType','scope','deliverables'],e);strings(r,p,['exclusions','milestones','responsiblePartnerId','responsibleManagerId','clientAcceptanceDate','draftDeliverableReference','internalReviewDate','clientPresentationDate','finalDeliverableReference','notes'],e);dates(r,p,['clientAcceptanceDate','internalReviewDate','clientPresentationDate'],e);if(!isNonNegative(r.budgetAmount)||!isNonNegative(r.budgetHours))e.push(`${p}.budgets must be nonnegative.`);}


function validateTimesheet(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,TIMESHEET_STATUSES,e);required(r,p,['staffId','activityCode','activityType','workDate','description'],e);strings(r,p,['engagementId','reviewerId','reviewDate','returnReason','notes'],e);dates(r,p,['workDate','reviewDate'],e);if(!isPositive(r.hours))e.push(`${p}.hours must be positive.`);if(!isBoolean(r.billable))e.push(`${p}.billable must be boolean.`);}
function validateExpense(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,EXPENSE_STATUSES,e);required(r,p,['expenseDate','expenseCategory','currency','description','claimedById'],e);strings(r,p,['engagementId','receiptReference','reviewerId','approvalDate','reimbursementDate','rejectionReason','notes'],e);dates(r,p,['expenseDate','approvalDate','reimbursementDate'],e);if(!isPositive(r.amount))e.push(`${p}.amount must be positive.`);}
function validateInvoice(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,INVOICE_STATUSES,e);required(r,p,['invoiceNumber','clientId','engagementId','invoiceDate','dueDate','serviceType','currency'],e);strings(r,p,['billingPeriod','billingBasis','billingStatus','preparedById','reviewerId','approvalDate','issueDate','fileReference','adjustmentReason','notes'],e);dates(r,p,['invoiceDate','dueDate','approvalDate','issueDate'],e);for(const f of ['grossAmount','discount','taxVatAmount','netAmount','amountCollected','outstandingAmount'])if(!isNonNegative(r[f]))e.push(`${p}.${f} must be nonnegative.`);if(isFiniteNumber(r.grossAmount)&&isFiniteNumber(r.discount)&&isFiniteNumber(r.taxVatAmount)&&r.netAmount!==r.grossAmount-r.discount+r.taxVatAmount)e.push(`${p}.netAmount is inconsistent.`);if(isFiniteNumber(r.netAmount)&&isFiniteNumber(r.amountCollected)&&isFiniteNumber(r.outstandingAmount)&&r.outstandingAmount!==Math.max(0,r.netAmount-r.amountCollected))e.push(`${p}.outstandingAmount is inconsistent.`);}
function validateCollection(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,COLLECTION_STATUSES,e);required(r,p,['collectionReference','invoiceId','clientId','engagementId','collectionDate'],e);strings(r,p,['method','bankCashReference','recordedById','reversalReason','notes'],e);dates(r,p,['collectionDate'],e,false);if(!isPositive(r.amount))e.push(`${p}.amount must be positive.`);}
function validateCommunication(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,COMMUNICATION_STATUSES,e);required(r,p,['clientId','communicationType'],e);strings(r,p,['engagementId','communicationDateTime','contactPerson','subject','summary','commitments','followUpOwnerId','followUpDate','confidentialityLevel','fileReference','amendmentReason','notes'],e);if(r.communicationDateTime!==''&&!isIsoDateTime(r.communicationDateTime))e.push(`${p}.communicationDateTime must be a valid date-time or empty.`);dates(r,p,['followUpDate'],e);if(!isBoolean(r.followUpRequired))e.push(`${p}.followUpRequired must be boolean.`);}
function validateFollowUp(r:Record<string,unknown>,p:string,e:string[]):void{requireBase(r,p,FOLLOW_UP_STATUSES,e);required(r,p,['followUpReference','sourceType','clientId','ownerId','dueDate','actionRequired'],e);strings(r,p,['sourceId','engagementId','completionComment','completedDate','cancellationReason','notes'],e);dates(r,p,['dueDate','completedDate'],e);if(!inValues(r.priority,PRIORITIES))e.push(`${p}.priority is invalid.`);}

const validators: Record<string, (r: Record<string, unknown>, p: string, e: string[]) => void> = {
  [STORAGE_KEYS.clients]:validateClient,[STORAGE_KEYS.clientContacts]:validateContact,[STORAGE_KEYS.staff]:validateStaff,[STORAGE_KEYS.engagements]:validateEngagement,
  [STORAGE_KEYS.engagementTeam]:validateTeam,[STORAGE_KEYS.engagementDeadlines]:validateDeadline,[STORAGE_KEYS.tasks]:validateTask,[STORAGE_KEYS.services]:validateMaster,
  [STORAGE_KEYS.clientCategories]:validateMaster,[STORAGE_KEYS.industries]:validateMaster,[STORAGE_KEYS.auditEvents]:validateAuditEvent,[STORAGE_KEYS.acceptanceReviews]:validateAcceptance,
  [STORAGE_KEYS.independenceAssessments]:validateIndependence,[STORAGE_KEYS.engagementLetters]:validateLetter,[STORAGE_KEYS.auditPlans]:validatePlan,[STORAGE_KEYS.planningMilestones]:validateMilestone,
  [STORAGE_KEYS.auditRisks]:validateRisk,[STORAGE_KEYS.auditMateriality]:validateMateriality,[STORAGE_KEYS.programmeTemplates]:validateTemplate,[STORAGE_KEYS.engagementProgrammes]:validateProgramme,
  [STORAGE_KEYS.workingPapers]:validateWorkingPaper,[STORAGE_KEYS.evidenceRegister]:validateEvidence,[STORAGE_KEYS.samplingRegister]:validateSampling,[STORAGE_KEYS.documentRequests]:validateRequest,
  [STORAGE_KEYS.documentRequestItems]:validateRequestItem,[STORAGE_KEYS.documentRequestReminders]:validateReminder,
  [STORAGE_KEYS.reviewNotes]:validateReviewNote,[STORAGE_KEYS.auditCompletionItems]:validateCompletionItem,[STORAGE_KEYS.auditFindings]:validateFinding,
  [STORAGE_KEYS.reportVersions]:validateReportVersion,[STORAGE_KEYS.managementLetters]:validateManagementLetter,[STORAGE_KEYS.representationLetters]:validateRepresentationLetter,
  [STORAGE_KEYS.reportIssues]:validateReportIssue,[STORAGE_KEYS.engagementLocks]:validateFileLock,[STORAGE_KEYS.amendmentRequests]:validateAmendment,
  [STORAGE_KEYS.managerReviewRecords]:validateManagerReview,[STORAGE_KEYS.partnerReviewRecords]:validatePartnerReview,
  [STORAGE_KEYS.listedComplianceItems]:validateListedCompliance,[STORAGE_KEYS.regulatoryDeadlines]:validateRegulatoryDeadline,[STORAGE_KEYS.auditCommitteeCommunications]:validateCommittee,
  [STORAGE_KEYS.qualityReviews]:validateQualityReview,[STORAGE_KEYS.keyAuditMatters]:validateKam,[STORAGE_KEYS.taxAssignments]:validateTax,[STORAGE_KEYS.vatAssignments]:validateVat,
  [STORAGE_KEYS.rjscAssignments]:validateRjsc,[STORAGE_KEYS.accountingAssignments]:validateAccounting,[STORAGE_KEYS.advisoryAssignments]:validateAdvisory,
  [STORAGE_KEYS.timesheets]:validateTimesheet,[STORAGE_KEYS.expenses]:validateExpense,[STORAGE_KEYS.invoices]:validateInvoice,[STORAGE_KEYS.collections]:validateCollection,
  [STORAGE_KEYS.communications]:validateCommunication,[STORAGE_KEYS.followUps]:validateFollowUp
};

export function validateModuleRecords(module: string, records: unknown): string[] {
  const errors: string[]=[]; const validator=validators[module]; if (!validator) return [`Unsupported module key: ${module}.`]; if (!Array.isArray(records)) return [`Module ${module} must be an array.`]; const ids=new Set<string>();
  records.forEach((record,index)=>{ const path=`${module}[${index}]`; if (!isObject(record)){errors.push(`${path} must be an object.`);return;} validator(record,path,errors); if (isString(record.id)){if(ids.has(record.id)) errors.push(`${module} contains duplicate id ${record.id}.`); ids.add(record.id);} }); return errors;
}
export function validateSettings(value: unknown): string[] {
  const errors:string[]=[]; if(!isObject(value)) return ['settings must be an object.']; required(value,'settings',['schemaVersion','appVersion','operatorName'],errors); if(!Number.isInteger(value.upcomingDeadlineDays)||Number(value.upcomingDeadlineDays)<1||Number(value.upcomingDeadlineDays)>365) errors.push('settings.upcomingDeadlineDays must be 1-365.'); if(!isNonNegative(value.expenseReceiptThreshold)) errors.push('settings.expenseReceiptThreshold must be nonnegative.');
  if(!isObject(value.numbering)) errors.push('settings.numbering must be an object.'); else { required(value.numbering,'settings.numbering',['clientPrefix','engagementPrefix'],errors); if(!isPositiveInteger(value.numbering.startingSequence)) errors.push('settings.numbering.startingSequence must be positive.'); if(!isPositiveInteger(value.numbering.numberPadding)||Number(value.numbering.numberPadding)>10) errors.push('settings.numbering.numberPadding must be 1-10.'); if(!isObject(value.numbering.referencePrefixes)) errors.push('settings.numbering.referencePrefixes must be an object.'); else required(value.numbering.referencePrefixes,'settings.numbering.referencePrefixes',['reviewNote','finding','invoice','documentRequest','amendment','collection','followUp','managementLetter','representationLetter'],errors); }
  if(!Array.isArray(value.statusSettings)) errors.push('settings.statusSettings must be an array.'); return errors;
}
export function validateMeta(value: unknown): string[] { const errors:string[]=[]; if(!isObject(value)) return ['meta must be an object.']; required(value,'meta',['schemaVersion','appVersion','initializedAt'],errors); if(!isString(value.lastBackupAt)) errors.push('meta.lastBackupAt must be a string.'); if(isString(value.initializedAt)&&!isIsoDateTime(value.initializedAt)) errors.push('meta.initializedAt must be a valid date-time.'); if(isString(value.lastBackupAt)&&value.lastBackupAt&&!isIsoDateTime(value.lastBackupAt)) errors.push('meta.lastBackupAt must be a valid date-time or empty.'); return errors; }
export function isAppSettings(value: unknown): value is AppSettings { return validateSettings(value).length===0; }
export function isAppMeta(value: unknown): value is AppMeta { return validateMeta(value).length===0; }
